### ISSUE TITLE
infantry crawling

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#100]
I am seeing infantry that crawl around for their entire lifespan. It looks as though they are spawned with behavior mode in STEALTH instead of AUTO.

**Comment by Xeno69** [comment]
Closing this. I've played on another server with the 4.05 version yesterday and not a single unit was crawling.
The mission doesn't spawn units with STEALTH behaviour, it's not used anywhere in the scripts.

I was already wandering when playing on your server. Have never before seen so much units crawling.

**Comment by longtimegamer** [comment]
I always seem to find the weird ones...

I may try to debug this further but I agree there is no evidence it is related to Domination.

**Comment by Xeno69** [comment]
Well, check your server settings, I mean the ones in your server profile.
https://community.bistudio.com/wiki/server.armaprofile#Arma_3
