### ISSUE TITLE
Sandstorm script - undefined variable after using admin spectate - serious log spam

### ISSUE THREAD

**Issue by Auge103** [Xeno69/Domination#11]
Got this error after using admin spectate on Altis:
```
14:18:38 Error in expression <e {true} do {
if (rain isEqualTo 0 && {!d_rscspect_on && {!(player getVariable ">
14:18:38   Error position: <d_rscspect_on && {!(player getVariable ">
14:18:38   Error Undefined variable in expression: d_rscspect_on
14:18:38 File scripts\fn_sandstorm.sqf [d_fnc_sandstorm], line 33
```
Tested in Eden editor SP & MP - 3.95 - default settings.
Just load the mission (Altis), enter admin spectate, exit admin spectate. Thats it.

It seems that this var gets set to false in init, then to true in
 https://github.com/Xeno69/Domination/blob/61b6500f4901464b1759075250777033ee7c5fcf/co30_Domination.Altis/x_client/x_f/x_ui/fn_adminspectate.sqf#L16
and finally to nil in the same file. 
https://github.com/Xeno69/Domination/blob/61b6500f4901464b1759075250777033ee7c5fcf/co30_Domination.Altis/x_client/x_f/x_ui/fn_adminspectate.sqf#L25
That doesn't seem quite right.

When this error occurs, the arma rpt file gets seriously spammed with this error - it had about 120.000 lines in it (and roughly 7mb filesize) after about a minute or two.

**Comment by Xeno69** [comment]
I've merged your fix
