### ISSUE TITLE
Zeus working with carrier

### ISSUE THREAD

**Issue by FighterD1** [Xeno69/Domination#112]
Hi Xeno,

I run a small game with just my friends and I. Normally I use Zeus a ton just to give us a leg up during the missions with the minimal amount of people we have. We love using the carrier.

Only issue I am facing is Zeus does not interact with the flight deck of the carrier (snapping units, objects, etc). Makes it almost impossible to place a Wasp down on the deck. Not sure if this has something to do with how the carrier is placed in mission. Was wondering if this could be looked at and fixed up in a future update?

**Comment by Xeno69** [comment]
Well, that's a Zeus issue and not a mission issue and I can't fix Zeus related things in a mission.

Some objects placed on a carrier bounce of the deck and crash. That is an A3 problem (I had to write scripts to fix it)

**Comment by FighterD1** [comment]
Ah, apologies for a useless ticket! Thought Zeus was able to place things on the deck as if it was land. Currently just phases through and places in water.

Thanks for the information though!

**Comment by Xeno69** [comment]
Does Zeus not support the ALT key to change the height of an object?

**Comment by FighterD1** [comment]
Only after placing an object I believe. Any vehicles under water will explode instantly. Making it difficult to place on deck. You could start on land and drag over, but that is extremely difficult.

Since zeus is in a mission some objects have physics applied as well. The moment you let go of any vehicle over the carrier (with no snapping) they take a nose dive.
