### ISSUE TITLE
CAS / Artillery splash is off location in CUP maps

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#116]
Artillery is always off-target in Takistan.  CAS and artillery is always off-target in Takistan and Sarahani.

Those maps are two examples but there are probably more.  CAS and artillery splash is usually off by several hundred meters.

**Comment by Xeno69** [comment]
I've just tested it with 1.96RC and the Domi 4.10 release version. Works perfectly fine on Takistan and Sahrani for me.

**Comment by longtimegamer** [comment]
Both artillery and CAS?

I will close this issue and try again when 1.96 is released.
