### ISSUE TITLE
parameter for Titan cooldown?

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#120]
Is it possible to add a parameter for the Titan cooldown?  As I understand it, changing the current cooldown requires code changes or modifying the database.

**Comment by Xeno69** [comment]
It can either be changed in the dom_settings SQL database table or in init\fn_preinit.sqf
Look for
d_launcher_cooldown

**Comment by Xeno69** [comment]
Set to 0 to disable it

**Comment by longtimegamer** [comment]
No mission parameter settable in the lobby?

Is there concern the number of parameters are too high?

**Comment by Xeno69** [comment]
Maybe in the next version...
