### ISSUE TITLE
Load saved ammunition from arsenal

### ISSUE THREAD

**Issue by ibwc** [Xeno69/Domination#122]
with hotkey Ctrl+O maybe load saved ammunition from virtual arsenal.
i'm added in file fn_arsenal_mod.sqf  this section:
after #include "..\x_setup.sqf"

ADDED:
[missionNamespace, "arsenalOpened", { 
disableSerialization; 
params ["_display"]; 
_display displayAddEventHandler ["keydown", "_this select 3"]; 
{(_display displayCtrl _x) ctrlShow false} forEach [44151, 44150, 44146, 44147, 44148, 44149, 44346]; 
}] call BIS_fnc_addScriptedEventHandler;

this code disabled all buttons except Close button.

**Comment by Xeno69** [comment]
Is that ranked mode? Or TT?

**Comment by ibwc** [comment]
Is that ranked mode and TT. All missions with VA.
