### ISSUE TITLE
low client fps on 4.20

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#124]
A player reported low client FPS on 4.20 (latest version from this afternoon).  Version 4.17 did not have that problem.

Let me know if I can add more information.  We can try to capture logs if it will help.

**Comment by Xeno69** [comment]
90% of the changes in 4.20 are from you, so tell me what's going wrong :)

**Comment by Xeno69** [comment]
Anyway, download 4.17 again and tell me if it has the same problems (I've reuploaded 4.17 again, it is the same as 4.20 but without the changes from you)

**Comment by longtimegamer** [comment]
I tried 4.17 + my new "overwatch" code and it works fine...

The diff of master and 4.17 shows some changes in ammobox handling... Maybe that is a cause?  I'm just guessing.  I don't see how the "overwatch" and variable name changes are causing the issue but anything is possible in Arma...

Unfortunately I can't reproduce this problem on my machine.  It was reported by another player.  I will test with him on 4.20 again and see if the logs show anything.

**Comment by Xeno69** [comment]
The ammo box handling can't cause it, it only executes when an ammobox gets dropped or loaded.

Please report back

**Comment by longtimegamer** [comment]
This may be related to using CUP items in loadouts on client when the server does not have CUP mods loaded.  Or something else.

It seems very unlikely to be related to my 4.20 changes but I will keep this issue open a bit longer, hope to test more this weekend.

**Comment by longtimegamer** [comment]
Confirmed, no problems.  I will close this issue.
