### ISSUE TITLE
Admin login

### ISSUE THREAD

**Issue by JeroenVBH** [Xeno69/Domination#125]
Hi Xeno, is there a way to modify your code so I can do uinit ID comparison instead of database for the admin slot in MP? I know I'm a noob but can't seem to find how to occupy the admin slot.

Any help is welcome!

**Comment by Xeno69** [comment]
There isn't a specific admin slot in Domi.

What you can do is edit the mission if you don't use a database. Open init\fn_preinit.sqf and search for either

> d_reserved_slot

or

> d_uid_reserved_slots

Check the comments on how to use them.

Still needs a game admin login which is only available via the games server.cfg (admin password)

**Comment by JeroenVBH** [comment]
Ok found d_uids_for_reserved_slots = ["largenumber"]; and added my ID.

Thing is this server does not have a server.cfg or any .cfg file. The mission is your Domintaion 4.20 based. Do you have a clue where else they could have pasted the Admin Password?

**Comment by Xeno69** [comment]
Well, if you use a dedicated server there should be a server.cfg

Check
https://community.bistudio.com/wiki/server.cfg
and
https://community.bistudio.com/wiki/ArmA:_Server_configuration

**Comment by JeroenVBH** [comment]
It hasn't:

http://pic100.picturetrail.com/VOL473/10806159/24809766/414372352.jpg

**Comment by Xeno69** [comment]
Well, you have to make one yourself, that's how it works :)

Getting up an Arma server can be quite frustrating but it isn not an Domination issue but a game issue.
