### ISSUE TITLE
wrong way of air taxi

### ISSUE THREAD

**Issue by pisamute** [Xeno69/Domination#127]
When ordering a taxi for the red side on altis, I am faced not the first time with the problem of incorrectly building the path to the base. Instead, the brave Mi8 flies to the place of an aircraft carrier, which is not on the map, because we are playing for the Reds. How to solve this problem?

**Comment by Xeno69** [comment]
Are you playing the vanilla Altis OPFOR version or what version do you play?

**Comment by pisamute** [comment]
4.21 version. I’m playing with RHS mod

**Comment by Xeno69** [comment]
I'll check it

**Comment by Xeno69** [comment]
I have checked the RHS Opfor version on Altis and I do not get the problem. The Mi8 flies nicely too the air base.

Can you provide me client and server RPT files?
https://community.bistudio.com/wiki/Crash_Files#Arma_3

**Comment by pisamute** [comment]
okay. I found what the problem was. the evacuation menu is done incorrectly; very poorly translated into Russian, the whole semantic load is lost: choose the point of place from where the helicopter picks up or the final destination for the delivery of already evacuated fighters. everything works great, thanks for your time.

**Comment by Xeno69** [comment]
If you have a better translation let me know:)
