### ISSUE TITLE
arsenal in tvt version

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#13]
In tvt version (vanilla), opfor havent "red arsenal". Only blufor.
http://joxi.ru/82QLB8KcjZ0yom
game with ranks

**Comment by Xeno69** [comment]
I'm currently working on finishing the missing ranked stuff like weapons, etc.
Just yesterday I've updated the weapons/arsenal file:
https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/i_weapons_default.sqf

**Comment by topden** [comment]
ok. but new "i_weapon_default.sqf" not open opfor arsenal in tvt version (i copy it and try) Opfor arsenal are clear

**Comment by Xeno69** [comment]
The new version is not for the current Domi version 3.98 because of many other internal changes.

You have to wait till 3.99 :)

**Comment by topden** [comment]
ok. good. thank u

**Comment by Xeno69** [comment]
Fixed in 3.99
