### ISSUE TITLE
LinuxServer

### ISSUE THREAD

**Issue by sunnus01** [Xeno69/Domination#133]
Downloaded last Release and getting this ["Dom Database result loading:","[0,""Database Config Error""]"]

Can't make connection to DB, am using mysql on linux Centos 7 and tried MariaDB on Win 7, no success..

[Main]
Version = 1

Randomize Config File = false
;; Randomizes Config File after loading.
;;   Recommend to turn on, if you have enabled filepatching on arma.

Allow Reset = false
;; Allows 9:RESET, usefull for development work

Thread = 0;
;; Option to force number of worker threads for extDB3.
;;   Min = 2, Max = 6

[Log]
Flush = true;
;; Flush logfile after each update.
;;    Option really only usefull if running DEBUG BUILD

[Database]
IP = 90.190.177.29 tied local ip like 192.168.1.220 nothing same eeror
Port = 7777
Username = arma3
Password =  mypassword
Database = domination

**Comment by sunnus01** [comment]
oh yeah and @exDB3, latest

**Comment by sunnus01** [comment]
and running all on Centos 7

**Comment by Xeno69** [comment]
Rename [Database] to [Domination]

**Comment by Xeno69** [comment]
Please check also
https://github.com/Xeno69/Domination/wiki/Database-setup

**Comment by sunnus01** [comment]
Yeah i just found it myself ! TY! for quick reply

**Comment by Xeno69** [comment]
Cool :)
