### ISSUE TITLE
havent art.call again

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#15]
3.99 TT version (ranked ver)
http://joxi.ru/52aBgKlC4Bgv0A

Opfor comander cant open menu art.strike too
http://joxi.ru/bmoJENgHxk7Exr

**Comment by Xeno69** [comment]
Works fine here. Have you scrolled the mouse wheel?

**Comment by topden** [comment]
ok. menu open only when see in laserdesignator, not "U" button. But artillery not fire. send video later

**Comment by topden** [comment]
menu open only when see in laserdesignator. ok. But artillery not fire. can send video

**Comment by topden** [comment]
https://youtu.be/Uu66pTBWW5w

**Comment by Xeno69** [comment]
You have only marked the artillery target but not called artillery.

Compared to old versions you have to mark artillery (not only artillery operators can do that but squad leaders too) and an artillery operator has to call the artillery strike via the Domination menu with Call Artillery

**Comment by Xeno69** [comment]
Or in other words...Some players can mark artillery targets but the artillery operator decides which target will be attacked

**Comment by topden** [comment]
on video i playing "artillery operator"'s slot. i click button "request artillery" and ...NOTHING! And in "domination menu-U" havent call artillery!

**Comment by Xeno69** [comment]
I'll check when I'm at home in a few hours
