### ISSUE TITLE
scores (tt, rank ver)

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#16]
If i destroy my heli (lift 1) i recive +3 score. I can farm))
http://joxi.ru/n2YXgExCo4kPWm
http://joxi.ru/YmE3zZMF0eGOlA

**Comment by Xeno69** [comment]
Download the following version, it fixes both your issues :)
https://drive.google.com/open?id=16KwsCmLJUmvRSUfMoK-IQ07PY5OsLd1h

**Comment by topden** [comment]
thanks, but not both...
