### ISSUE TITLE
cluster artillery always missing target

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#169]
Cluster artillery is always off by 100-200m.  Other artillery types are fine.  Or am I going crazy?

**Comment by Xeno69** [comment]
Hm, afair I've removed cluster ammo...

`{
	_magsv pushBackUnique _x;
} forEach (_marray select {getText(configFile>>"CfgAmmo">>getText(_cfgmagx>>_x>>"ammo")>>"submunitionAmmo") != "Mo_ClassicMineRange"});`

**Comment by longtimegamer** [comment]
I'm referring to the cluster ordnance in the artillery menu (see image):

![image](https://user-images.githubusercontent.com/46298219/87104214-3b23c580-c225-11ea-9b3e-8ad3211f74dc.png)

I should change the description to "sometimes missing target" but it is happening very frequently for me.

**Comment by longtimegamer** [comment]
Does the artillery use randomization?  Or does it fire exactly on the target position?

**Comment by longtimegamer** [comment]
Some images of cluster artillery splash vs marked location... Is this normal?

![image](https://user-images.githubusercontent.com/46298219/87109395-8c868180-c232-11ea-933d-f2f69f8d068b.png)

![image](https://user-images.githubusercontent.com/46298219/87109419-a031e800-c232-11ea-8ab7-8eb891581eae.png)

![image](https://user-images.githubusercontent.com/46298219/87109466-c061a700-c232-11ea-992e-e9a9a2f498a8.png)

**Comment by longtimegamer** [comment]
Here is a laser strike (no problem, perfect accuracy):

![image](https://user-images.githubusercontent.com/46298219/87109771-81802100-c233-11ea-9674-7d9a849ff3fe.png)

...and with 155mm HE (also no problem, wide spread but good accuracy):

![image](https://user-images.githubusercontent.com/46298219/87110035-16831a00-c234-11ea-8d8a-f87ad2153433.png)

**Comment by Xeno69** [comment]
The only difference is that only one artillery vehicle fires when a cluster shell is selected (to reduce lag). Other than that it is exactly the same as with all other shells.

**Comment by longtimegamer** [comment]
Hmmm ok.  I will close this issue and re-open if I find something later.
