### ISSUE TITLE
ARTILLERY!!!

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#17]
DEAR XENO!  i download last u version again and:
**- without ranks (tt) artillery working now),** BUT:
**- WITH RANKS -NOT WORKING!** WHY? becouse see message http://joxi.ru/E2ppEJqT9bVgy2
http://joxi.ru/D2Pdz7Lcpl1O92
(i have 66666 scores and art.observer slot)
i think its script error or database config? On other servers some people fix it and say me, that u have some error in database. pls check again.
I cant open this dialog http://joxi.ru/eAOWzydhxQE3xA  .Only in without ranks version.

**Comment by Xeno69** [comment]
There is a more serious problem behind it. I think I found the issue already but had no time before work to fix it.

I'll take a look when I'm back from work in 11 hours

**Comment by topden** [comment]
thx

**Comment by Xeno69** [comment]
I've fixed it in b7f492452427c0e0378c5d9b518ef7edb33a248f but found another problem which needs some more love and testing (it's database related).
Hope to get it fixed tomorrow.

Will do a maintenance/hotfix release soon!

**Comment by topden** [comment]
ok. waiting fix...
