### ISSUE TITLE
Flag Town

### ISSUE THREAD

**Issue by Wick89** [Xeno69/Domination#171]
we have a bug, when the flag base is down you can not take it!?
need to restart mission over and over again

**Comment by Xeno69** [comment]
What do you mean with flag base?

**Comment by Wick89** [comment]
if camper destroy we can not take flag

**Comment by Xeno69** [comment]
Destroy camps? You can't destroy camps.

Could pelase ask someone to translate for you? I currently do not really understand what you mean exactly. Thank you!

**Comment by Xeno69** [comment]
Closing for now. Reopen if the problem occurs again (please with better description, thank you)
