### ISSUE TITLE
Some question again)  (tt vers)

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#18]
Artillery working-thx)
1. Baer or Bear?
http://joxi.ru/LmGn9RMieK001r
2. after respawn on base player stay on second floor in barracks building. sometimes its may to kill player by texture or smth more. need to change marker place
http://joxi.ru/vAWOzGnS1a007A
3. WHY add spectator in tt version for any players?? for best game??))) http://joxi.ru/a2Xnz0Xi1MYGpr
pls delete this and give only admins.
4. Bonus vehicles spawn on marker 0 (i dont remember mission.sqm name marker), not on base. All bonuses spawns on this marker. and opfor too. http://joxi.ru/BA0G5wohJ9D6E2
5. can I change the menu of the earplugs on the buttons? it is not very convenient to get them through your menu. for example, the button F1 or F2 or etc.
6. If i change sides i recive new scores, but old congratuletions). and waiting few minutes i recive all my scores from orther side http://joxi.ru/eAOWzydhxQX1QA.
7. and its NOT NORMAL, that player can change side. Maybe u can block it for 30 minutes for example? because on the server the people are switching over to the other side and watching where the mhq and so on and then go back. and catch everyone there is no time and desire. +And again your magic spectator for everyone)
8. and it would be nice to add to the mission of the ability to transfer scores from player to player ...

9. and add random start main targets after restart mission, becouse not interested to fight in the same cities, which start the same way. http://joxi.ru/a2Xnz0Xi1MGyNr   first town in every versions(( tt or coop

10. and after respawn player have all loot again http://joxi.ru/VrwzEjdcObP86A  . Its no good.

**Comment by Xeno69** [comment]
1 - 4 already fixed/changed...

Just keep it coming :)

**Comment by Xeno69** [comment]
5 also resolved. You can change earplugs with user key 15 (you have to assign a key yourself in the game settings)

**Comment by Xeno69** [comment]
9 is what you can do yourself already, just change d_MainTargets_num to a number > 0 in description.ext or the SQL database or in the server lobby (Main Targets)

**Comment by Xeno69** [comment]
Regarding 10.... Which respawn do you actually mean? When the player respawns before he gets revived or at base/MHQ/Farp?

When a player respawns at base/MHQ/Farp he gets the gear he had when he closed Virtual Arsenal... After a revive he just gets the gear he had before the revive.

**Comment by Xeno69** [comment]
New release available, please open a new issue if you find more issues :)

https://drive.google.com/open?id=1C2H2onEPlrLzbVyqzwwfWLy5DzwkyBaE

**Comment by topden** [comment]
many thanks for fixes and updates. Special thanks for

`- Added: You can now put your earplugs in and out with user action key 15 (you have to set a key in the game/A3 control settings yourself, user 15!)
- Changed: In the TT version players have to wait 30 minutes (outside the running mission) to switch sides, otherwise they get kicked to the lobby of the current server
- Fixed: Do not show the "Nearby informed players:" message in spectating when a player has no lives left
- Fixed: Disable spectating respawn button exec if player has no lives left
- Fixed: Players who connect again immediately and have no revive lives left can play again
- Added: Transfer score to another player dialog in ranked mode`

**Comment by topden** [comment]
> Regarding 10.... Which respawn do you actually mean? When the player respawns before he gets revived or at base/MHQ/Farp?
> 
> When a player respawns at base/MHQ/Farp he gets the gear he had when he closed Virtual Arsenal... After a revive he just gets the gear he had before the revive.

after respawn need to gets the gear to player he had before the die (like before revive). Player must go to arsenal time to time and update his ammunition without capability "specialy die for quickly reload his ammo". Maybe next version?)

**Comment by topden** [comment]
Sorry for stupid question) how to check transfer scores? cant find special menu or other... Or need some players on server for menu?

**Comment by Xeno69** [comment]
Correct, needs at least one more player on the server

**Comment by topden** [comment]
and last question. Can i help u with russian text for xml file?
because some of the other people you mention do not speak Russian well and badly write)

**Comment by Xeno69** [comment]
Yes please!

**Comment by topden** [comment]
9. I did not mean the number of cities, but their random appearance regardless of the number. because every time you start a mission, the list of cities starts from the same city.
