### ISSUE TITLE
extDB3 MIA

### ISSUE THREAD

**Issue by brian2** [Xeno69/Domination#184]
Haven't been able to find extDB3 via the Documentation bitbucket link.
I did find @Torndeco s github account but not extDB3 in particular.
Is extDB3 still the database glue layer?  Is there an alternate source?
I can help with docs & DBs but not much help with C++.

**Comment by Xeno69** [comment]
Oh, you are right, the bitbucket site is gone. Have you already asked in the Bohemia Interactive forums ExtDB3 thread?

Currently no idea if there is an alternative download location

**Comment by Xeno69** [comment]
Here is at least a temporary one

https://github.com/SteezCram/extDB3
