### ISSUE TITLE
high number of spawned active scripts

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#185]
I am seeing server performance problems after the server runs for a long period of time.  I was curious about the number of active scripts and was surprised to find the number was so high...

diag_log ['activeScripts', diag_activeScripts];

[1790,0,0,48]

Wow!  There are 1,790 scripts running after the mission was online for 3 days...

Any ideas what might cause this?

**Comment by longtimegamer** [comment]
The mission was using some special Domination AI features (AI awareness and more).  I will try to reproduce the issue with "default" mission parameters and add some trace logging.

**Comment by longtimegamer** [comment]
Ok after some tests... This is not a problem with "default" Domination.  With default parameters the number of active scripts is stable. I tested this with ~20 captured maintargets and the diag_activeScripts is ~110 and steady.

Since this doesn't affect default Domination parameters I will close this issue for now.  However the awareness script may be leaving active scripts. I will keep investigating and might need to reopen later.

**Comment by Xeno69** [comment]
Well, the `while {true} do {` loop in fn_hallyg_dlegion_Snipe_awareness.sqf never ends, even if a unit is dead or deleted.

**Comment by Xeno69** [comment]
https://github.com/Xeno69/Domination/commit/b021d23ab6492f395dec8aed0974ab535039c565

I've added some !alive checks to the while loop. It should now end when the unit is no longer alive and fix the issue

**Comment by longtimegamer** [comment]
Yes that was it, zombie awareness scripts.  With a high enemy group count the server would freeze after approximately 7 maintargets were cleared.

![image](https://user-images.githubusercontent.com/46298219/92008016-9ac5bb00-ed14-11ea-8626-e48d68e496e4.png)

Thanks for the fix!
