### ISSUE TITLE
mini-camp objects are not correctly placed on the ground and hover in the air

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#189]
Floating objects around the mini-camp.  This is a problem on Altis and Malden and maybe others.

![image](https://user-images.githubusercontent.com/46298219/93669220-93b2e280-fa60-11ea-8909-5e79bb4b8991.png)

**Comment by Xeno69** [comment]
Specific island and/or mod/addon? I've never seen it even with 40 players on a server

**Comment by longtimegamer** [comment]
No mods.  I have seen this bug on every map (including CUP maps) since the mini-camps were added.  It is easy to reproduce.  Almost every maintarget shows at least a one object floating in the air.  I see it in almost every game session...

**Comment by Xeno69** [comment]
I have exactly never seen the problem on any map :( Not once.

**Comment by Xeno69** [comment]
Whatever I try, I can't reproduce it :(

**Comment by longtimegamer** [comment]
Maybe from the pull request I submitted in 5/2020 and `d_EnableSimulationCamps`...

```
if (_superSimple) then {
	//World coords are used
	_object = createSimpleObject [_p3d, _pos, _loc];
} else {
	if (d_EnableSimulationCamps > 0) then {
		_object = createVehicle [_class, _pos, [], 0, "NONE"];
	} else {
		//ASL coords are used; fixed later by ASL to World offset
		_object = createSimpleObject [_class, AGLToASL _pos, _loc];
	};
};
```

Something with createVehicle vs createSimpleObject and position translation... I probably broke something but I don't think anyone else uses that setting.  :)

**Comment by longtimegamer** [comment]
#139 looks really suspicious.  I removed some AGLToASL and I don't remember why...

**Comment by longtimegamer** [comment]
Everything seems to be working correctly.

This commit and diff for fn_createsimpleobject.sqf is interesting:

https://github.com/Xeno69/Domination/compare/b5602f1..247a87e#diff-a5d7c45397850422ff53b8ebfb509f0672bf004fac78cfaeadfc1ee1dfbd0a98

In that old commit I changed from `_pos` to `AGLToASL _pos`.  I'm not sure how it worked before that change.  When I remove `AGLToASL` the tents and other items are always underground.

I am not sure why or how I was seeing the previous problem.  I will close this issue since it works correctly now.
