### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#19]
a small request for design. Can you move the positions in the screenshot slightly so that the text does not merge? Because:
- Russian translation a little longer is obtained in different places
- players with different extensions on the computer see this text in different ways
And in this table there is free space for editing  http://joxi.ru/YmE3zZMF0vD17A
it's not critical, but it would look perfect http://joxi.ru/EA44Lwoiwnx4wA

**Comment by Xeno69** [comment]
Positions changed
