### ISSUE TITLE
when running local MP player loses Zeus when killed

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#190]
Steps to reproduce:

* open Domination in Eden and run as multiplayer
* press Y and do Zeus stuff
* get killed
* press Y and no Zeus stuff :(

**Comment by longtimegamer** [comment]
I found a discussion that might be relevant. I want to fix this so I will try.

https://forums.bohemia.net/forums/topic/226612-adminlogged-zeus/

**Comment by longtimegamer** [comment]
This is not high priority to me but I would like to leave this issue open.  I might have a chance to look at it sometime.

**Comment by Xeno69** [comment]
Imo this can only be fixed by BI

**Comment by longtimegamer** [comment]
Hmmm ok.  I will close this now and re-open if something changes.
