### ISSUE TITLE
cannot load any previous loadouts in virtual arsenal when CUP upgrades occur

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#191]
When playing Chernarus2020 with Domination no previous loadouts can be used.

Previous loadouts in the ammobox are displayed as available (white text and the loadout name can be clicked and selected) but when the player exits the virtual arsenal view the weapons are replaced with the previous weapon with no ammo.  When a new profile is created and weapons are saved this works as expected.

This might be related to CUP upgrades and/or Domination inventory check or likely both.  It appears any CUP upgrade will invalidate all player loadouts.

**Comment by longtimegamer** [comment]
Maverick commented on this in Steam forum.  I think the mod loadouts are compatible between minor releases.  Also the previous loadouts are not disabled (greyed-out) in the virtual arsenal so a player will select them and expect them to work.  CUP had a few updates in a row and I noticed this behavior was presented after each update.  Players were required to create all new loadouts because all of the old loadouts showed this bug.

**Comment by Xeno69** [comment]
It works exactly as expected. As long as d_arsenal_mod is 0 all weapons/uniforms/etc which are not part of CUP get removed once Virtual Arsenal closes (only possible then).
If d_arsenal_mod is 1 that check isn't done and you can use whatever stuff you want in VA.

I'm using some CUP stuff in VA for 2 years already and it never got removed.

Loadouts shown is something hardcoded in VA, nothing I can do about. Seems it just checks if a mod is available and not if the classname is in the VA array.

**Comment by longtimegamer** [comment]
Hmm interesting.  The d_arsenal_mod setting is default on my servers but when I run CUP Domination the problems happen as I describe.  It's odd that yours has been stable for 2 years and we are not so lucky.

The hardcoded loadouts shown do seem to be hardcoded in VA.  A few of my loadouts have been disabled because they used assets that were no longer present in the loaded mods.  It does seem to just check if the mod is available.  I am not sure what you mean by classname however.  Is that what is strict arsenal setting is doing?

I will test if the problem is solved by just turning off the strict arsenal check.

**Comment by longtimegamer** [comment]
Cool looks like it works.  Closing.
