### ISSUE TITLE
respawn

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#20]
coop opfor rhs

does not work respawn if you change the number of lives in the settings. we put 5 and could not be reborn either on the base or on the kshm. The menu is active but there is no action. log errors http://joxi.ru/RmzoE6ZH07dPR2
try to default (-1) but too, cant respawn

**Comment by topden** [comment]
coop malden blufor rank revive - working (without sqldata)
coop altis opfor rhs rank revive - NOT working (too)
tt altis vanilla rank - NOT working
If u want to try turn on ranks and http://joxi.ru/J2bBgZqCXllN32

**Comment by Xeno69** [comment]
Already fixed in my internal version

**Comment by topden** [comment]
ok. i check again/ and if i turn next parametrs:
http://joxi.ru/4Aklg1qTyYYzVr
i can respawn inmidiatly (without wait 90 sec) and havent time to revive
http://joxi.ru/l2Zx4jkUwBBoDr

**Comment by Xeno69** [comment]
Also already fixed in my internal version

I'll release a new one tomorrow, want to test a little bit before I release

**Comment by topden** [comment]
ok. How can I transfer the xml file with the translation? I'm not familiar with git-hub. maybe  e-mail?

**Comment by Xeno69** [comment]
Upload it to your Google drive or Microsoft Onedrive and make it sharable or provide some other download link

**Comment by Xeno69** [comment]
Upload it to your Google drive or Microsoft Onedrive and make it sharable or provide some other download link.

Would be nice if you could make it available now so I can add it today:)

**Comment by topden** [comment]
ок. and I changed the translation of three sentences in this place. Instead of describing medicine, I wrote about the transfer scores. you can fix this text to your  English version, because this is more important information)
http://joxi.ru/V2V3bMOFxNJEwA

Now I'm checking out another text and in a couple of hours I'll put a link here

**Comment by topden** [comment]
forgot yet. in the tt version, if one side has captured the city, then it does not change its color (blue or red), it still remains green.  Its not big error, but ....

**Comment by topden** [comment]
i dont know why, but some text not change ingame from xml. for example
http://joxi.ru/12M5zk6cM6bjw2
i write russian, but http://joxi.ru/Vm64ZwoiDQdZPA
=========
http://joxi.ru/a2Xnz0Xi1J5Xpr
http://joxi.ru/DrlBgy0CveOPL2

**Comment by Xeno69** [comment]
Please also note that there are 4 new entries in stringtable.xml and some have changed

https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/stringtable.xml

**Comment by Xeno69** [comment]
https://github.com/Xeno69/Domination/commit/c0c810261faf79403021d7c25a23c76523a36cfd

**Comment by topden** [comment]
https://drive.google.com/open?id=1Myv_ykgn7ZOF7IHumzp6tNCXUx9PYbsw
хмl with last chanche. +4 new entries
