### ISSUE TITLE
RHSUSAF bug 

### ISSUE THREAD

**Issue by SamsonSeth** [Xeno69/Domination#202]
Hi .. 
after last updates of Domination there is a wired bug with RHSUSAF weapons ..
for example 
when i equip HK416 and Angle Forward Grip upon exiting arsenal my character is placing his weapon on his back and pulling out sidearm in proces of doing so one magazine for HK416 is vanishing from Inventory 
also  this process / bug occurs every time i press  " I "  for inventory .. upon exit  same thing happens ..

**Comment by Xeno69** [comment]
Doesn't happen for me. I select and equip it with the AFG and all is fine.

But I don't use all addons/mods being used on Dorps server. Maybe a problem with conflicting addons.

**Comment by SamsonSeth** [comment]
i tested it on a few server with only RHSUSAF running and on all of them i have the same thing .. it started to happening after last Dom /  RHSUSAF updates .. i enter the server for example the HUD DK 1 go to arsenal pick up the weapon equip it with AFG TAN and upon exit one magazine disappears or i enter the server with already saved gear press I once nothing .. press I second nothing .. and after third time press I there is animation of character placing weapon on his back and losing one magazine ...  and after that every time i press I to check inventory ..when weapon has AFG or other such girp from RHSUSAF  ... after the bug started to happening  it also wont let me save loadout  doesn't refresh the changes ...
 the problem doesn't appear on servers running Liberation RX for example .. 
i was submitting the bug to RHS in first place .. but they said it must be Dom mission fault  

Http://feedback.rhsmods.org/view.php?id=5971
