### ISSUE TITLE
small question

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#21]
coop rhs altis rank:
http://joxi.ru/5mdBgRqCkYObQA
1.side mission with convoy start from base need change start position marker some meters.
2. AI patrol near base are vanilla, not rhs blufor  http://joxi.ru/EA44Lwoiwn63KA
3. have any time to recive heli to base? we waiting heli 2 two hours and it not respawn http://joxi.ru/GrqGjqphQwEZV2
Farps:
need container down http://joxi.ru/KAxJBQLHMpElDm
and in flag-menu write "qudrobike", but respawn gaz tigr

**Comment by Xeno69** [comment]
3. is normal, chopper only respawns when destroyed. Chopper 1 (Lift chopper) respawns when no player is in it after some time

**Comment by Xeno69** [comment]
All fixed
