### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#22]
hi, dear Xeno. Its 99.99% russian translation of xml. Only 5-6 lines are not translated, as I have never seen them in missions. but maybe someone will add them. Speech in them about any "codenames..."
https://drive.google.com/open?id=1Kt177Y6pnF0v8Fqi0lG3YhkMzZif1O5q
Thank you.

**Comment by Xeno69** [comment]
Added in 6cc09a2141515c5597a7018a636f352de5c38375
