### ISSUE TITLE
CfgRemoteExec mode = 1 breaks zeus modules

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#231]
https://github.com/Xeno69/Domination/blob/08d4274b26041e178c56eaa45345948bb0bb1bc2/co30_Domination.Altis/description.ext#L111

Just a heads up, an admin is unable to use Zeus modules with the new mode setting for CfgRemoteExec.  This includes skip-time and changing the weather.  Just something to consider.

**Comment by Xeno69** [comment]
Three solutions:
1. BI fixes it
2. Change mode to 2 (makes everything unsafe)
3. Add the functions or script commands Zeus uses to CfgRemoteExec in description.ext

**Comment by longtimegamer** [comment]
1. I created an issue, we will see what happens: https://feedback.bistudio.com/T155036
2. that sounds bad...
3. How does this work?  Would it require adding each command manually?  Or perhaps I can add the Zeus key to whitelist another way, maybe put in keys/ directory...

I set my server config verifySignatures = 2 because of hackers but would prefer something better...

**Comment by Xeno69** [comment]
verifySignatures makes it harder but doesn't stop them.

CfgRemoteExec with mode 1 only allows remoteExec functions and scripting commands to be send over the network when they are defined in description.ext class CfgRemoteExec.
So script kiddies (they are no hackers) can no longer send code (scripts) over the net and execute them wherever they want.
And it also can limit execution to the server or clients.

Now what you have to do is to check all functions pbo files in the game folder and find the ones which are Zeus related and then find the script files where they send skiptime/date etc commands and add those commands/functions  to CfgRemoteExec.

But be aware, don't add functions like BIS_fnc_spawn/ececVM or whatever functions might execute code on other clients and/or the server.

And limit a script command like skiptime to the server only.

**Comment by Xeno69** [comment]
I've just checked the functions in the Curator folder... BI uses BIS_fnc_MP for everything in Zeus.

Funny enough, this is from the BIS_fnc_MP Wiki page:

`This function is now provided for backward compatibility only. Please use the engine based commands remoteExec or remoteExecCall instead.`

https://community.bistudio.com/wiki/BIS_fnc_MP

Anyway, BIS_fnc_MP uses remoteExec internally so you have to find which scripting commands and which functions are transfered in Zeus and add them to CfgRemoteExec in description.ext

**Comment by longtimegamer** [comment]
Hmmm I usually only use SkipTime and Weather modules...  I could just add those two commands but it is unfortunate to lose Zeus functionality for everything else.

As an alternative perhaps there can be a new parameter for security mode 0/1/2 ?  I would like to fix this issue however when I have time and we have a good plan...

**Comment by Xeno69** [comment]
Parameters can't change the modes.

Closing this. Something BI has to change, don't they still run public Zeus servers?

If someone really needs that Zeus functionality he/she can change the mode in description.ext manually.

For most servers it isn't needed and to be honest, I prefer security over two or three missing Zeus features :-)

**Comment by longtimegamer** [comment]
Ok.  I will go back to mode=2 and continue to use verifySignatures.

It's true someone can still execute remote commands but... these "hackers" need someone to write a mod for them to cheat.  I haven't had any disruptions with the mods restricted.
