### ISSUE TITLE
I want to contribute about internationalization - Chinese

### ISSUE THREAD

**Issue by XinLau1996** [Xeno69/Domination#249]
Dear author friends, excuse me, I am an arma3 game enthusiast and a java developer. I want to provide some Chinese language support for this project, stringtable.xml . My email address: xiaotaiye1996@gmail.com .

**Comment by Xeno69** [comment]
Hello,

thanks for helping.

You can find the stringtable.xml file here: [Stringtable](https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/stringtable.xml)

Text files with missing string names can be found here: [Missing translations](https://github.com/Xeno69/Domination/tree/master/missing_translations)

**Comment by XinLau1996** [comment]
OK, according to your prompt, I have finished the Sinicization, but I don't have enough permission to push it to GIT

**Comment by Xeno69** [comment]
Can you upload the file somewhere?

What ,you can also do is a pull request
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by XinLau1996** [comment]
I pulled your warehouse and updated it. You can see it here https://github.com/XinLau1996/Domination

newly added： https://github.com/XinLau1996/Domination/blob/master/README.zh_cn.md

to update： https://github.com/XinLau1996/Domination/blob/master/missing_translations/Chinese.txt
                    https://github.com/XinLau1996/Domination/blob/master/co30_Domination.Altis/stringtable.xml

**Comment by Xeno69** [comment]
Closing this now, thanks for the translation :)
