### ISSUE TITLE
CAS on civilians do not incur score penalty

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#258]
Calling CAS on civilians does not penalize the player.

**Comment by longtimegamer** [comment]
I will take a look at this since it is probably in the civilian code.

**Comment by Xeno69** [comment]
I think you don't need to check "d_who_fired" as the killer is already set correctly with setShotParent as soon as the arty itself fires.

"d_who_fired" is just so that I can set the object with setShotParent immediately.

**Comment by longtimegamer** [comment]
Thanks for the comment.  PR #259  should fix this issue.

**Comment by Xeno69** [comment]
Closing it
