### ISSUE TITLE
radiotower hard to destroy

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#270]
It's very difficult to destroy the new radiotower... Is there a way to make it easier to destroy?  I have climbed to the top and planted a satchel several times.

**Comment by Xeno69** [comment]
I've played several times on a server with 30-40 players and no one had a problem with it. I also blower up one, just needed two satchels

**Comment by longtimegamer** [comment]
Two satchels?  Before I always used only one directly in the center of the radiotower (the large explosive satchel charge).

I attempted to plant one large satchel on the top level of the green tower, somewhere near the radiotower.  I thought I "missed" the radio?  Or now does it require two?

**Comment by longtimegamer** [comment]
I suspect the satchel is now further away and less damage requires two?  Not sure.

**Comment by Xeno69** [comment]
I always needed two satchels

**Comment by longtimegamer** [comment]
Can this be changed?  :)

I would like for one satchel to destroy the tower.  I was thinking of attaching an event handler to the tower and make the damage higher.  Or maybe a marked spot that is clear to the player where a satchel will always destroy the tower?

It is very easy to "miss" the tower or do very little damage.

**Comment by Xeno69** [comment]
I always had to use 2 satchels... Even before adding the additional tower. 

Do you use vanilla satchels or mod satchels?

**Comment by Xeno69** [comment]
I've added a little bit more damage to the tower handle damage EH...

**Comment by longtimegamer** [comment]
Thank you!

Sorry, I missed your comment earlier.  I use a vanilla large satchel explosive.  I found a location on the back of the "crow's nest" where one satchel works but it was difficult to learn the spot.  I think your damage EH is much better, players just want to see the tower fall down.
