### ISSUE TITLE
Unable to use Bipod attachments

### ISSUE THREAD

**Issue by Ultradar** [Xeno69/Domination#271]
Currently I am trying to setup a server for Domination 4.48 RHS Opfor Altis

However, I've noticed that when you try to use a bipod attachment on a weapon, you can't equip the weapon. It just removes the magazine from your inventory until there are none left. Once there are no magazines left, you can then equip your weapon again.

Able to reproduce this every time with the following:

AK105(Zenitco), Any magazine, RK-2 bipod grip. 

Appears to only be affecting RHS AFRF weapons, but using any bipod I am able to recreate the issue. 

This doesn't happen in standard editor. Just in domination.

**Comment by Xeno69** [comment]
Fixed for the next release... Two bipods/grips were missing in the check resulting in the issue you described.
