### ISSUE TITLE
Error: can't resize AutoArray to negative size!

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#282]
dedicated server crashes over time with an error message:

"Error: can't resize AutoArray to negative size!"

**Comment by Xeno69** [comment]
Please make a ticket at the BI feedback tracker if you encounter a crash, add the crash files.

I doubt that this is a mission error as I have not even an idea what an AutoArray should be.

**Comment by longtimegamer** [comment]
This happens on a linux dedicated server.  Unfortunately the only crash log produced is a 2GB core file.

This is probably not related to Domination but I wanted to document this problem for visibility.

I created a ticket:

https://feedback.bistudio.com/T158507

**Comment by longtimegamer** [comment]
I forgot to answer your previous question.  No, this is not using performance/profiling branch.

Someone commented on the ticket.  It looks like some other missions are having the same problem on CamLaoNam.  🤷‍♂️
