### ISSUE TITLE
"d_with_ranked" not being read correctly with extDB3 and HeidiSQL.

### ISSUE THREAD

**Issue by SaltySeabiscuit** [Xeno69/Domination#286]
Mission does not correctly read the value of "d_with_ranked" when using external SQL database on dedicated server and enables ranked mode regardless of its set value.

**Comment by Xeno69** [comment]
It doesn't enable ranked mode but some points based stuff that ranked also uses.

So not a bug or issue but wanted behaviour. Or better, does exactly what I wanted :)

**Comment by SaltySeabiscuit** [comment]
gotcha, thanks for the clarification on that!
