### ISSUE TITLE
"Domination.sql" Generates "dom_params2"'s "param_value" column in SmallINT, requiring change to INT to use some infinite settings.

### ISSUE THREAD

**Issue by SaltySeabiscuit** [Xeno69/Domination#287]
Not so much a Bug as a QOL issue. As in the title the SQL is generated with SmallINT, which requires changing to INT to use the infinite options of some settings ("d_maxnum_tks_forkick ", "d_WreckDeleteTime ", "d_WreckMaxRepair ", "d_drop_max_dist "). 

Not a particularly large issue but just thought it worth pointing out.

**Comment by Xeno69** [comment]
Yeah, I've changed already a few for the last release. Need too look over it again when I find time.

**Comment by longtimegamer** [comment]
@Xeno69

Is this because a number is too large? or because it is negative?  are negative numbers allowed?

**Comment by Xeno69** [comment]
Negative numbers are allowed but the database handling made positive numbers out of negative.

**Comment by longtimegamer** [comment]
Are you thinking about doing a DB migration script for this?

There is a mess in the params with 0 or 1 as true.  It is all my fault since I started using "1" for true.  If there is an opportunity then maybe we can standardize.

**Comment by Xeno69** [comment]
I won't change that as otherwise others might be even more confused and it will cause problems.

In Domination for Arma Reforger :)

**Comment by Xeno69** [comment]
Closing this as it is already changed
