### ISSUE TITLE
AI stuck in hunched over animation - acinpknlmstpsraswrfldnon "Standing still while dragging another unit"

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#288]
AI are stuck in a hunched over position.  AI begin a "drag" animation immediately after spawn and become stuck in that animation forever.

Linked to this ticket:

https://feedback.bistudio.com/T156969

**Comment by longtimegamer** [comment]
This bug is still present.  Maybe there is some way to avoid this animation?

I noticed this may be used by fn_swm.sqf in some places.

**Comment by longtimegamer** [comment]
Or maybe this `setUnitPos "UP"` is a problem and interrupts the animation?

https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/server/fn_garrisonUnits.sqf#L38

**Comment by Xeno69** [comment]
I have never seen this. Only players can drag and carry other players in Domination. AI can only heal. So no idea where this comes from.

**Comment by longtimegamer** [comment]
It's certainly not a Domination bug but maybe something we can avoid.  I am still testing this issue so I'll leave it open for a little while.  I want to test the fix provided by Freddo3000, something like this:

```
        _one_unit addEventHandler ["AnimChanged",{
		params ["_unit","_anim"];
		if (_anim == "acinpknlmstpsraswrfldnon") then {
			_unit playMoveNow "amovppnemstpsraswrfldnon";
		};
	}];
```

**Comment by Xeno69** [comment]
This will be  a quite costly change because it will constantly trigger animchanged EHs for AI units.

I have never seen this before, ever in the last 20 years playing the series. Is there a way to trigger it somehow?

**Comment by longtimegamer** [comment]
I was afraid of that.  Many new event handlers.  :|

This is with a Linux dedicated server.  It happens immediately when the mission starts but with different levels of reliability.  For instance, it only happens maybe 1:5 starts on Altis but on CamLaoNam it happens more often.

When I start a server I use Zeus to look at the enemies to verify the mission isn't in this broken state and when I want to reproduce the issue I try the SOG map because that is where the bug happens most.  I can watch the units being spawned at the target center and I can see the reach-down animation and the freezing.  I don't know what causes the units to use reach-down instead of raise-gun-up animation which is the normal way a unit is spawned.

This bug has been reported by a couple of people in the Domination Steam comments, not sure how many servers are affected.  It might be a Linux-only thing.  The workaround right now is to check the server after every restart and kill the server if it's bugged.

**Comment by longtimegamer** [comment]
I don't know how to proceed with this bug.  It sometimes feels like we are trying to fix the Arma engine itself.  I will close this issue for now, maybe reopen if there is a solution.
