### ISSUE TITLE
viewdistance fog cannot be disabled

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#296]
I have been attempting to disable the viewdistance fog with no success.

Players starting at Altis can usually see south for approximately 6km but only for ~30 seconds.  Then something turns on viewdistance fog.  I don't know if this fog is from Domination or the game engine.  The code in Domination seems to "fight" the engine weather.

I have tried setFog, setOvercast, setRain, edited the Map Intel, disabled fn_weathersever.  None of those worked.

For testing purposes I am trying to force the viewdistance to 10km and remove this fog.  Any ideas @Xeno69 ?

**Comment by longtimegamer** [comment]
I am closing this since it is not a real issue, only for discussion.  I appreciate any suggestions.

**Comment by Xeno69** [comment]
Open the Dashboard, uncheck the main target viewdistance checkbox and it's gone.

**Comment by longtimegamer** [comment]
It works, thanks!
