### ISSUE TITLE
remoteExec functions with JIP need jip=1 in description.ext

### ISSUE THREAD

**Issue by Xeno69** [Xeno69/Domination#312]
See above

**Comment by longtimegamer** [comment]
@Xeno69 seems like 4.55 is broken, target will not spawn using the mission from the 7zip release

**Comment by longtimegamer** [comment]
@Xeno69 are fixes going to A3_DEV now?

**Comment by Xeno69** [comment]
Yes, I'm using A3_DEV because of new A3 2.06 scripting commands.

You can still use master, I merge them into A3_DEV
