### ISSUE TITLE
Extdb3 work, Intercept don't.

### ISSUE THREAD

**Issue by Evaexe117** [Xeno69/Domination#315]
Hello, 
i'm trying to host a domination server.

Extdb3 work ( connect and update player and server config)
But when i use Intercept, nothing append on the database.
Crendital and database config are ok ( work with EXTDB3)

I'm on Ubuntu server 20.04 x64bits !

`CallExtension 'intercept' could not be found
CallExtension 'intercept' could not be found
11:10:56 Intercept Invoker test result: ==
11:10:56 Error in expression < {false};

[_extensionName,_signalName] interceptSignal _parameters;

11:10:56 Error position: <interceptSignal _parameters;

11:10:56 Error Missing ;
11:10:56 File z\intercept\rv\addons\core\signal.sqf..., line 23
11:10:56 Error in expression < {false};

[_extensionName,_signalName] interceptSignal _parameters;

11:10:56 Error position: <interceptSignal _parameters;

11:10:56 Error Missing ;
11:10:56 File z\intercept\rv\addons\core\signal.sqf..., line 23
11:10:56 Intercept Invoker initialized.
11:10:56 Intercept Pre-Init...
11:10:56 Intercept Pre-Init Completed.
11:10:57 [CBA] (xeh) INFO: [20790,90.772,0] PreInit started. v3.15.5.210713
11:10:57 [CBA] (settings) INFO: Reading settings from settings file.
11:10:57 [CBA] (settings) INFO: Finished reading settings from settings file.
11:10:57 [CBA] (xeh) INFO: [20790,90.994,0] PreInit finished.
11:10:57 "############################# co40_domination_4_55_blufor co30_Domination #############################"
11:10:57 [20790,90.994,0,"Executing Dom fn_preinit.sqf"]
11:10:57 ["Dom d_with_ace:",false]
11:10:57 "DOM InterceptDB domination.sqf file found!"
11:10:57 Error in expression <
D_DB_CON = dbCreateConnection 'domination';

11:10:57 Error position: <'domination';

11:10:57 Error Missing ;
11:10:57 Error in expression <
D_DB_CON = dbCreateConnection 'domination';

11:10:57 Error position: <'domination';

11:10:57 Error Missing ;
11:10:57 Error in expression < then {
_query = dbPrepareQueryConfig _cname;
} else {
_query = dbPrepareQu>
11:10:57 Error position: <_cname;
} else {
_query = dbPrepareQu>
11:10:57 Error Missing ;
11:10:57 Error in expression < then {
_query = dbPrepareQueryConfig _cname;
} else {
_query = dbPrepareQu>
11:10:57 Error position: <_cname;
} else {
_query = dbPrepareQu>
11:10:57 Error Missing ;
11:10:57 Error in expression < then {
_query = dbPrepareQueryConfig _cname;
} else {
_query = dbPrepareQu>
11:10:57 Error position: <_cname;
} else {
_query = dbPrepareQu>
11:10:57 Error Missing ;
11:10:57 Error in expression < then {
_query = dbPrepareQueryConfig _cname;
} else {
_query = dbPrepareQu>
11:10:57 Error position: <_cname;
} else {
_query = dbPrepareQu>
11:10:57 Error Missing ;
11:10:57 Error in expression <
private _query = dbPrepareQueryConfig 'getTop10Players';
private res = D_DB>
11:10:57 Error position: <'getTop10Players';
private res = D_DB>
11:10:57 Error Missing ;
11:10:57 Error in expression <
private _query = dbPrepareQueryConfig 'getTop10Players';
private res = D_DB>
11:10:57 Error position: <'getTop10Players';
private res = D_DB>
11:10:57 Error Missing ;
11:10:57 "Dom InterceptDB domination.sqf loaded and compiled"
11:10:57 ["Dom Intercept DB created:",any]
11:10:57 ["DOM d_database_found:",true,"d_db_type:",1]
11:10:57 "Dom Database result loading dom_settings:"
11:10:57 [20790,90.999,0,"Executing Dom initcommon.sqf"]
11:10:57 [20790,91.038,0,"Dom initcommon.sqf processed"]
11:10:57 Weather was forced to change
`

**Comment by Xeno69** [comment]
For intercept you need to start the server with
-filepatching

**Comment by Evaexe117** [comment]
this is my launcher
I tested with -filepatching before "mod" and after
`./arma3server_x64 -profiles=serverprofile -port=2302 -bepath=battlEye -cfg=config.cfg -config=server.cfg  "-mod=@CBA_A3;" "-serverMod=@InterceptDB" -filepatching
`

**Comment by Xeno69** [comment]
I haven't used Linux for years so I guess I'm not of much help here.

**Comment by Xeno69** [comment]
Closing. Please check the Domination Discord server. There are people who run a A3 server on Linux and can maybe help
