### ISSUE TITLE
Khe Sanh?

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#331]
Any plans to make Domination for the new SOG map?

I see Khe Sanh has one large military base in the center and many small villages around the map.  I have been using the new dynamic enemy cnt settings to make many small locations work, for example d_occ_cnt=-2 instead of d_occ_cnt=4 so the enemy is based on the terrain and number of buildings.  The maintarget is usually well balanced regardless if it is a large city or a small village.

**Comment by Xeno69** [comment]
No plans for the new SOG map.

I won't do any ports to other maps/islands.

**Comment by Xeno69** [comment]
Finally found time to check the new SOG island, well, I've seen better maps :(

**Comment by longtimegamer** [comment]
Heretic!  I love it!

I hacked up a PBO by copy/pasting the other SOG x_setup and mission files.  I don't think everything works properly (CAS and airdrop) but it is playable for testing purposes.  I'm running with the dynamic "low" settings for occupy/ambush/overwatch and d_grp_cnt_footpatrol=6 with ~15 small locations.  I think the extra footpatrol helps the jungle gameplay.

![image](https://user-images.githubusercontent.com/46298219/135663018-28634a2e-0fdd-4836-bf5d-ad116f2e8025.png)

This is a screenshot from Khe Sanh (headless client with extra enemies)

![image](https://user-images.githubusercontent.com/46298219/135663292-454836ed-d9e4-4125-83c5-a86e423ff1e2.png)

**Comment by longtimegamer** [comment]
My love for Khe Sanh was short.  Not worth it.

The pathfinding seems to be completely broken.  In the screenshot above the foot patrols near the rice fields did not move at all.

**Comment by longtimegamer** [comment]
Another note, this solution by johnnyboy fixes the rice paddies:

https://forums.bohemia.net/forums/topic/234952-enable-prairie-fire-dlc-ai-to-navigate-rice-paddies/

**Comment by Xeno69** [comment]
Na, I don't want to check where all those rice paddies are and do yet another workaround for engine problems.

**Comment by longtimegamer** [comment]
I added a quick fix.

Gorgeous maps, playing both lately.
