### ISSUE TITLE
cannot pick up weapons lying around when playing unranked

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#333]
I can't pick up weapons from dead AI since the weapons disappear.  No mods and server is unranked.

**Comment by Xeno69** [comment]
I have just tried on a dedicated server, no problems at all.

I need a weapon class name.

**Comment by longtimegamer** [comment]
Ok maybe I am crazy...

I will reopen this issue if I see it again.

**Comment by longtimegamer** [comment]
@Xeno69 remember this old bug?  I think your recent commit fixed it!

https://github.com/Xeno69/Domination/commit/22bbeb372342e33cfcf84027a2b264b9aa460a9e

**Comment by longtimegamer** [comment]
Something is weird here...

The server is using only default parameters.  If I pick up a .50 cal sniper rifle from a dead Opfor sniper then the rifle disappears.  Is this expected behavior if the player is low rank?

If the server is using CUP then all weapons disappear even when unranked.

The only way I can stop this behavior is to remove `call d_fnc_ptakeweapon` in fn_setupplayer.sqf:

https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/client/fn_setupplayer.sqf#L302

**Comment by longtimegamer** [comment]
```
I have just tried on a dedicated server, no problems at all.

I need a weapon class name.
```

When I try on a dedicated server, the new weapon in my hand disappears and my old primary weapon re-appears.  This happens for any weapon including non-DLC and non-mod weapons (example: the Katiba).

parameters:

d_with_ranked = 1; // no
d_save_to_mpns = 0; // no
d_arsenal_mod = 1; // no

**Comment by longtimegamer** [comment]
If d_fnc_ptakeweapon is only for NVGs then maybe we can skip that function?  I don't know why ptakeweapon is forcing this weapon problem but I don't think the function needs to run on a server that disables rank and does not force remove NVGs.

BEFORE

```
// available in non ranked versions too, removes nvg if without nvg is activated to avoid cheating
player addEventhandler ["Take", {call d_fnc_ptakeweapon}];
```

AFTER

```
// available in non ranked versions too, removes nvg if without nvg is activated to avoid cheating
if (d_with_ranked != 1 && { d_without_nvg != 1 }) then {
	player addEventhandler ["Take", {call d_fnc_ptakeweapon}];
};
```

**Comment by longtimegamer** [comment]
I added the expression in this commit:

95ff4813502fb57bc970b458510d283c55d0f0d1

let me know if you want a different solution

**Comment by longtimegamer** [comment]
Ok, this does not fix the actual bug but it will prevent ptakeweapon from running when the bug occurs.  Maybe that is sufficient.

**Comment by longtimegamer** [comment]
this fix is part of
https://github.com/Xeno69/Domination/pull/607

**Comment by longtimegamer** [comment]
I forked this a while ago until I can understand what you are trying to do.  From a player perspective, it is simply broken for many years.

**Comment by longtimegamer** [comment]
make this...

```
player addEventhandler ["Take", {call d_fnc_ptakeweapon}];
```

...into this...

```
if (!d_with_ranked && { d_without_nvg != 1 }) then {
	player addEventhandler ["Take", {call d_fnc_ptakeweapon}];
};
```

Why not?

Is it better to add another server parameter?  d_please_please_please_disable_ptakweapon is a good name.

**Comment by longtimegamer** [comment]
@Xeno69 it would be nice to fix this before the next release

**Comment by longtimegamer** [comment]
is this ok?  this adds another parameter but it works.

https://github.com/Xeno69/Domination/pull/636
