### ISSUE TITLE
maintarget unexpectedly done

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#349]
I am seeing rare cases where the maintarget is suddenly magically marked done.  In these cases there is still one or more HQs that are not captured and some red squares in the target area.  With those conditions the mission suddenly reports the target cleared and the map icon becomes a green circle and target voting selection begins for the next location.

**Comment by longtimegamer** [comment]
I will turn on some debug logs and see if I can capture some details.

**Comment by Xeno69** [comment]
Hm, what settings do you use? I mean params.

**Comment by longtimegamer** [comment]
d_ao_check_for_ai = 0

Different question: is there a way to turn on ALL debug or is it only for each file?

**Comment by Xeno69** [comment]
Simply set the debug define in x_setup.sqf instead of a normal script file.

If set in x_set.sqf it will turn on debug in every file

**Comment by Xeno69** [comment]
So anything new here?

**Comment by longtimegamer** [comment]
Nothing new.  The issue occurred again but even with debug settings the log does not show any obvious error.  I plan to add some logging to trace this problem.  I will leave this issue open and add notes.

**Comment by Xeno69** [comment]
I've played 4.57 today on a 30 player server and we didn't have that issue.

Maybe a specific params setting?

**Comment by longtimegamer** [comment]
I think this is it:

https://github.com/Xeno69/Domination/commit/c824682b762559036296638b65dc009ec029ea59

This happens when we have cleared almost all of the enemies and then the timer auto-resolves the maintarget.  Sometimes players will hunt down remaining enemies in the red squares and do not try to capture the objectives so the workaround script executes instead.

I think this is playing "as designed" so I will close this issue.

**Comment by Xeno69** [comment]
Ahh, yeah, I've introduced it because sometimes it happened that AI was spanwed under a rock when a camp was near a rock. In that case it was impossible to end a main target because players couldn't take the camp.

I really really hope that Enfusion solves issues like those.
