### ISSUE TITLE
d_cur_tgt_pos doesn't get set when using sidemissions only

### ISSUE THREAD

**Issue by Auge103** [Xeno69/Domination#37]
When using the option "sidemissions only", everytime an enemy gets killed or a building gets destroyed, the corresponding eventhandler scripts will throw errors because of an empty d_cur_tgt_pos variable:

```
Error in expression <f (!isNil "d_cur_tgt_pos" && {_building distance2D d_cur_tgt_pos < 800}) then {
>
Error position: <distance2D d_cur_tgt_pos < 800}) then {
>
Error 0 elements provided, 3 expected
File x_server\x_f\fn_buildingchanged.sqf [d_fnc_buildingchanged], line 36
```
```
Error in expression <ctParent _unit && {_score > 0 && {_unit distance2D d_cur_tgt_pos < d_mttarget_ra>
Error position: <distance2D d_cur_tgt_pos < d_mttarget_ra>
Error 0 elements provided, 3 expected
File x_server\x_f\fn_handlescore.sqf [d_fnc_handlescore], line 40
```

d_cur_tgt_pos currently only gets set in https://github.com/Xeno69/Domination/blob/e637f2721420ae091b9c201508e1baa57d9d58ff/co30_Domination.Altis/x_server/x_f/fn_createnexttarget.sqf#L23

**Comment by Xeno69** [comment]
It also gets set to an empty array in d_init.sqf which causes the 0 elements error...

**Comment by Xeno69** [comment]
Fixed internally... Not at home, will push later
