### ISSUE TITLE
error when calling CAS with no laser designator

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#379]
The code should support CAS without a laser but when a player uses it with binoculars then the CAS mission never fires and stuck in state of "CAS is unavailable."

` 8:26:45 Error in expression 
_pos = [0,0,0];
if (isNull _target) exitWith {hintSilent "No>
 8:26:45   Error position: 
 8:26:45   Error isnull: Type Array, expected Object,Group,Script,Config entry,Display (dialog),Control,Network Object,Task,Diary record,Location
 8:26:45 File mpmissions\__cur_mp.cam_lao_nam\scripts\fn_moduleCAS_guidedmissile.sqf..., line 27`

**Comment by longtimegamer** [comment]
This only occurs on the special maps (Vietnam, IFA, GM etc).

`if (!d_ifa3lite && {!d_gmcwg && {!d_unsung && {!d_csla && {!d_vn}}}}) then {`

Other maps require a laser designator so this is not an issue on most maps.  I will look at it sometime soon.

**Comment by longtimegamer** [comment]
see #381 for fix

**Comment by Xeno69** [comment]
Closing
