### ISSUE TITLE
Maps?

### ISSUE THREAD

**Issue by RacerXx** [Xeno69/Domination#380]
Xeno is there more than one map in the repository?  We running takistan now but are there others included in this repository if so where can i find the list?

**Comment by Xeno69** [comment]
https://github.com/Xeno69/Domination/wiki/Versions-and-needed-mods-addons

You will find all versions in the 7z download files at the release page (for example Domination_4_58_compiled.7z and Domination_4_58_uncompiled.7z)
https://github.com/Xeno69/Domination/releases/latest

**Comment by RacerXx** [comment]
yes thank you i see them now so do these server parameters apply to all maps in the release? https://github.com/Xeno69/Domination/wiki/Params

**Comment by Xeno69** [comment]
The paramus are valid for all versions.
