### ISSUE TITLE
Add also Base to viewdistance reduction setting in Dashboard/Status Dialog

### ISSUE THREAD

**Issue by Xeno69** [Xeno69/Domination#397]
Only Main Target currently displayed but does also reduce viewdistance at base.

**Comment by babulya95** [comment]
Здравствуйте подскажите пожалуйста у вас есть канал на ютубе и как можно включить чаты в Арма 3 на сервере чат рации и есть ли у вас миссия где можно покупать ботов в миссиях? 
--
Отправлено из Mail.ru для Android пятница, 01 апреля 2022г., 00:25 +09:00 от Alexander Olk  ***@***.*** :

**Comment by Xeno69** [comment]
I don't have a YouTube channel.

The radio channels can be enabled by editing the description.ext of the mission:
https://github.com/Xeno69/Domination/blob/9a51c6ef5226fb2abcb166d433a90f5628b7fb32/co30_Domination.Altis/description.ext#L97

I don't have a version where you can buy AI.

(I hope google translate was correct)
