### ISSUE TITLE
Respawn/teleport position is not coherent with selected position in GUI

### ISSUE THREAD

**Issue by Auge103** [Xeno69/Domination#40]
Issue:
When selecting a spawn point in the teleport or respawn GUI, the selected position in the list is not the same as on the map, nor does it spawn the player at the selected position.
This apparently happens when using more than 2 MHQ's, but I'm quite unsure with that.

Trace example:
(variable names only valid for this example, those are not from the original mission)
- Respawn list array of `BASE, Mhq1, Mhq2, Mhq3, CARRIER, Farp1, Farp2, Farp3` in that particular order, from top to bottom.
- Since only the `d_additional_respawn_points` have this issue, we are only looking at their corresponding classnames (array has those names in exactly this order, exluding additional info like positions for better readibility): 
`d_add_farp_d_flag_bb`->`CARRIER`
`d_add_farp_d_flag_bb_2`->`Farp1`
`d_add_farp_d_flag_bb_1`->`Farp2`
`d_add_farp_d_flag_bb_3`->`Farp3`

UI workflow:
1. Player opens the UI.  `fn_teleportdialoginit.sqf `gets called, each marker gets correctly drawn.
Selection in `fn_update_telerespsel.sqf` is at 
`_data: "D_BASE_D"`, `_sel: "7"` ,`_uidx: "0"`, `d_beam_target: "D_BASE_D"` which are all correct so far.
2. Player selects the last entry **"Farp3"**. `fn_update_telerespsel.sqf` is correct again:
`_data: "d_add_farp_d_flag_bb_3"`, `_sel: "0"` ,`_uidx: "-1"`, `d_beam_target: "d_add_farp_d_flag_bb_3"` 
3. **Next up is `fn_beam_tele.sqf`, where the issue is visible:**
When the player pushes the TP/respawn button, this script gets its own `_uidx` value:
https://github.com/Xeno69/Domination/blob/2729cfd5c38ee4092955af1a9f1040e2a1a6e6e9/co30_Domination.Altis/x_client/x_f/fn_beam_tele.sqf#L60
But this time, the `_uidx` comes from `d_add_resp_points_uni`, not `d_additional_respawn_points`.
Which has this array inside:
`d_add_farp_d_flag_bb_3"",""d_add_farp_d_flag_bb"",""d_add_farp_d_flag_bb_1"",""d_add_farp_d_flag_bb_2"",""d_add_farp_d_flag_bb"",""d_add_farp_d_flag_bb_2"",""d_add_farp_d_flag_bb_1"",""d_add_farp_d_flag_bb_3`
(yes, somehow it has every value twice)

**Since we get a `_uidx` value of 0 in this example** (`d_add_farp_d_flag_bb_3` is the first entry), **but the following code uses the `_uidx `for selection in another array,**
https://github.com/Xeno69/Domination/blob/2729cfd5c38ee4092955af1a9f1040e2a1a6e6e9/co30_Domination.Altis/x_client/x_f/fn_beam_tele.sqf#L63
**we get the wrong position. `d_add_farp_d_flag_bb ≠ d_add_farp_d_flag_bb_3 `**
In this case Farp3 is selected, respawn happens at the carrier.

A pretty similar codebase can also be found in `fn_buttonclickrespawn.sqf`, although I didn't found a use for this codefile yet. 

I didn't try to solve this issue so far, since I'm a bit time limited.

**Comment by Xeno69** [comment]
I've tried to reproduce it (with a third MHQ). Working as it should.

Check the variable names you are using.

**Comment by Auge103** [comment]
Damnit, somehow one change managed to slip through into my internal version. I'm terribly sorry for wasting your time, this one's on me.
Root cause: This change didn't get deleted:
https://github.com/Xeno69/Domination/commit/1d6ce7dd1c7952591da0d48655fbdb2ca5320aac#diff-ea1861e7d01e312573cf4ee87a8d5bc4

I'll reproduce all future issues a second time on the latest git version before posting them here, so this won't happen again.
(At least this bug helped me understand the UI part a bit better, so something was gained.)
