### ISSUE TITLE
AI spawns inside containers on Tanoa 

### ISSUE THREAD

**Issue by Xeno69** [Xeno69/Domination#413]
AI spawns in containers on Tanoa which can't be opened.

Maybe related to occupy.

**Comment by Xeno69** [comment]
Maybe add a check that cheks if it is a specific containee and don't spawn in there

**Comment by longtimegamer** [comment]
fixed

blacklist
cargo_hq_v1_f.p3d
cargo_house_slum_f.p3d

bf0905ce7b667371304f7045ba68ffc251bbbd58

reopen and report more buildings here to add to the blacklist
building names can be found in the logs, can usually guess which one is bad
