### ISSUE TITLE
enemy AI patrol groups can spawn inside rocks

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#414]
I am running a game with more patrol groups and I have noticed more enemy AI spawning inside rocks.  I looked at the spawn position and it looks like the enemy group formation may place some of the units in rocks.  Then when the patrol moves to the first waypoint the AI stuck in the rocks are left behind.

**Comment by longtimegamer** [comment]
to help reproduce the issue:

* increase the patrol count `d_grp_cnt_footpatrol` to a large number
* increase the group size `d_grp_size_override` to "high"
* play on a map with lots of rocks

**Comment by Xeno69** [comment]
I don't know if there is a good fix for it, that's an ooooold Arma issue

**Comment by Xeno69** [comment]
I have activated mchelper again.

Maybe a lineIntersects check can be added too, something like this:

`params ["_unit"];
private _pos = getPosATL _unit;
private _start = +_pos;
_start set [2, 100];
while {lineIntersects [ATLToASL _start, ATLToASL _pos]} do {
	_pos set [2, ((_pos select 2) + 0.25)]
};
_unit setPosATL _pos;`

**Comment by Xeno69** [comment]
I've added lineIntersects, should be ok now (I hope)
