### ISSUE TITLE
Civilians don't work on dedicated with HC

### ISSUE THREAD

**Issue by Auge103** [Xeno69/Domination#44]
Just tested this, if an HC is connected, no civilians are being spawned at all.
Just the dedicated without HC works fine.

I also have the feeling that something is off regarding the civilian unit count. I set
```
Civ enabled: true
Civ unit count: 2
Civ group count: 5
```
and there were at least 30 civilian units present in the MT. This doesn't sound right?

**Comment by Xeno69** [comment]
Well, they are created by BI modules, what did you expect?  :D

**Comment by longtimegamer** [comment]
Uh oh... what did I break?  :)

Looks like two issues.  I will open a separate issue for civ count.

Regarding HC+civ... If possible, can we discuss that here?  What should I do to fix it?  I have not tested civs with HCs but I will try.  However, any advice is appreciated.

**Comment by Xeno69** [comment]
I have completely refactored the code and moved it so it only runs on the server even if there is a headless client @longtimegamer, please wait till I push the changes in a few hours (still at work for some hours)

Server only should be better for BI modules

**Comment by longtimegamer** [comment]
Understood.  I will watch for commits, thanks.

**Comment by Xeno69** [comment]
Fixed by moving it to server side (because of BI modules) on case a HC is connected
