### ISSUE TITLE
AI awareness stops when fn_utowerkilled sets d_mt_spotted to false

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#444]
I just noticed this: destroying the radiotower sets d_mt_spotted to false

when the radiotower is destroyed the AI instantly stop all awareness behavior, no aggressive shooting, no special reload, no sniper awareness

**Comment by longtimegamer** [comment]
looking here

https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/server/fn_utowerkilled.sqf#L11

can we we move this to fn_target_clear?

**Comment by longtimegamer** [comment]
relevant here

https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/scripts/fn_hallyg_dlegion_Snipe_awareness_loop.sqf#L8

**Comment by longtimegamer** [comment]
`d_mt_spotted` is used in several places

I added another variable instead, should allow AI to fight until fn_target_clear is run

https://github.com/Xeno69/Domination/pull/445/files

**Comment by Xeno69** [comment]
I think it can be moved (d_mt_spotted that is) but I can't remember why I've put it in there.

**Comment by longtimegamer** [comment]
I noticed `d_mt_spotted` is also used for enemy artillery and some other stuff.  I think the new property is safer, should be no problem.
