### ISSUE TITLE
combat drone uses infantry viewdistance

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#449]
Infantry viewdistance is applied while flying a combat drone.

Steps to reproduce:

* d_save_to_mpns = 0
* d_enable_extra_cas = 1
* set infantry viewdistance to a low value
* fly somewhere and deploy the MHQ
* create a combat drone
* click "Control Gunner" (must **use the turret camera** to see the bug)
* click "release UAV controls"
* check the Domination dashboard
* observe the viewdistance is not expected value (air viewdistance)

**Comment by longtimegamer** [comment]
@Xeno69 any suggestions to fix or troubleshoot?

**Comment by Xeno69** [comment]
Yeah, but I'm not near my PC till tomorrow

**Comment by Xeno69** [comment]
For now check here:
https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/client/fn_vdhandler.sqf

**Comment by Xeno69** [comment]
Please check
https://github.com/Xeno69/Domination/commit/5bc1ad915cd257c2e8eeac6742a8681e97f39752

**Comment by Xeno69** [comment]
Mkay, will check in the next days.

**Comment by longtimegamer** [comment]
I am also using these settings:

d_InitialViewDistance = 1000;
d_ViewdistanceChange = 2; // server sets, client may change later

**Comment by longtimegamer** [comment]
I am able to easily reproduce this bug.  I edited the steps above in the top post.  Please review.

Did you try with the combat UAV turret control?  That steps seems to cause the bug.

**Comment by longtimegamer** [comment]
It seems to set view distance here:

https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/client/fn_uav_check.sqf#L30

the while loop exits when the player chooses "release UAV controls" but the viewdistance stays set at d_ViewDistanceAir

maybe after getConnectedUAV player returns null do:

`if(_uav is a greyhawk) then { updated vd}`

**Comment by longtimegamer** [comment]
I added a fix for review.

https://github.com/Xeno69/Domination/pull/469
