### ISSUE TITLE
mpmission Western sahara not working with last dlc vers

### ISSUE THREAD

**Issue by ghost** [Xeno69/Domination#455]
Hello, Xeno!
https://steamdb.info/depot/233791/manifests/
DLC has been updated 6 October 2022
After update dlc on server - mission not started (missing files)
What to do? Thanks for a great mission!

**Comment by Xeno69** [comment]
Just trried the latest Domination version with Western Sahara CDLC, works just fine.

Are you sure the server and the clients are running the WS CDLC?
