### ISSUE TITLE
Some issues with handlescore eventhandling

### ISSUE THREAD

**Issue by Auge103** [Xeno69/Domination#46]
First of all, _I'll soon push a fix for the first two issues mentioned here_. Testing done without mods.
We'll begin with the three simple ones:
1.  [fn_handlescore.sqf](https://github.com/Xeno69/Domination/blob/e6d29308803ada326eaa6bb948b47cb438b1708b/co30_Domination.Altis/x_server/x_f/fn_handlescore.sqf) gets triggered additional times per kill after each respawn in a hosted environment for the host itself. This can be abused to farm infinite points.
This is due to [this line](https://github.com/Xeno69/Domination/blob/0f1d39bf887ab225252e0f47cdcbfa5f2c4968cc/co30_Domination.Altis/x_client/x_f/fn_prespawned.sqf#L19) not having an isServer check - since the host itself never loses the initial eventhandler added in [initPlayerServer.sqf](https://github.com/Xeno69/Domination/blob/a2749f9c6c6f06ab8bdad9e510097a53be8aadb9/co30_Domination.Altis/initPlayerServer.sqf#L132). (Only remote units lose it after respawn)

2. Landing with a parachute can cause an airVec teamkill awarded (score only). This can be mitigated in handleScore.sqf.

3. (Didnt push because I was not sure if bug or feature): The bonus score in range of MT patrols is set as [addscore (score * 2)](https://github.com/Xeno69/Domination/blob/e6d29308803ada326eaa6bb948b47cb438b1708b/co30_Domination.Altis/x_server/x_f/fn_handlescore.sqf#L24) - since we already get one point from the kill itself, this adds two additional points. Is it intended to get thrice the points per kill in MT? Else it should be `addScore ((_score * 2) - _score)` (Gets worse if airkill - awards 15 points)

**4. The main one and actually hard to debug:**
On a dedicated server with a connected HC, the `handleScore` eventhandler which triggers [fn_handlescore.sqf](https://github.com/Xeno69/Domination/blob/e6d29308803ada326eaa6bb948b47cb438b1708b/co30_Domination.Altis/x_server/x_f/fn_handlescore.sqf) is somehow not reliable. The EH fires on most infantry against infantry kills, but when the player is inside a vehicle, suddenly a lot of kills, especially against other vecs, don't trigger the EH - despite Arma itself awarding points to the player.
I did test this quite a bit and it only occurs with a connected HC on dedicated (Didn't test hosted with HC).
Reproduction steps:
- add `[format ["|-> HS EH triggered on unit: %1 <-|",(_this # 0)]] remoteExecCall ["systemchat", 0];`  [below params in handlescore.sqf](https://github.com/Xeno69/Domination/blob/e6d29308803ada326eaa6bb948b47cb438b1708b/co30_Domination.Altis/x_server/x_f/fn_handlescore.sqf#L9), then load the mission on hosted or dedicated without HC first. Enabling the debug console for dedicated in the desciption helps here.
- Spawn yourself any combat vehicle like `_test = "B_Plane_CAS_01_dynamicLoadout_F" createVehicle position d_artop_1;`. Also `allowDamage false` for yourself helps.
- Start killing enemy vehicles. For every single kill one message should pop up in systemchat, also a score should be awarded on the scoreboard. This works fine so far.
- Repeat this as foot soldier in the main target or anywhere where you can shoot at AI's. Watch for message & scoreboard

- Now test this on a dedicated server with a connected HC unit. Repeat the whole test. You won't get any messages for most of the kills from a vehicle, but then again, most of the kills done as foot soldier will spawn a message. **BUT: You will get a score on the scoreboard for each and every kill.**
This is completely against what the EH should do.

I'm personally out of ideas and not quite sure if the "handleScore" EH is broken somehow.

**Comment by Xeno69** [comment]
3. is wanted behaviour. If you are playing as inf you get more points than for example a jet pilot or tank gunner when you are in the AO/main target area.

Let's call it some kind of balance :)

**Comment by Auge103** [comment]
I've built a little testmission for 4. - seems like I found a BI bug.
The eventhandler is in fact broken when a HC is connected and spawning enemy units.
Killing them doesn't trigger "handleScore" at all, but score gets added nevertheless.

I think you can close this one if you cannot think of some kind of workaround for this.
(I didn't find any working solution for my ScoreV2 module. Maybe BI will fix it some day)

**Comment by Xeno69** [comment]
Ok... closing
