### ISSUE TITLE
players sometimes respawn at squad leader when another location is selected and d_respawnatsql == 2

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#486]
occasionally a player will respawn at the wrong location

steps to reproduce:
* get killed
* select "Base" and click respawn
* sometimes you are respawned at the squad leader marker

it does not happen frequently, not sure about the cause

**Comment by AssadRajab** [comment]
This happened to me too,
I think that the issue is even if we select "Base" the script does not really switch the spawn location. This can be solved by just pressing again on base, so 2 clicks should prevent this issue. not the best thing to do but it works.

**Comment by Xeno69** [comment]
Is there an easy way to reproduce this? I've tried everything but it never happens (even only with friends).

**Comment by longtimegamer** [comment]
hard to reproduce, maybe reopen this issue later if needed
