### ISSUE TITLE
Air force setup

### ISSUE THREAD

**Issue by YukikazeMua** [Xeno69/Domination#493]
In which file is the refresh time of enemy air force changed

**Comment by Xeno69** [comment]
It's a combination of player numbers and d_airai_respawntime:
https://github.com/Xeno69/Domination/blob/76ada3597a0079ff0b356dc2d8412224d53da9b2/co30_Domination.Altis/init/fn_preinit.sqf#L1598

See also:
https://github.com/Xeno69/Domination/blob/76ada3597a0079ff0b356dc2d8412224d53da9b2/co30_Domination.Altis/server/fn_airai.sqf#L334

**Comment by YukikazeMua** [comment]
How do I change enemy attack aircraft

**Comment by Xeno69** [comment]
You can change it here:
https://github.com/Xeno69/Domination/blob/76ada3597a0079ff0b356dc2d8412224d53da9b2/co30_Domination.Altis/init/fn_preinit.sqf#L1439

**Comment by YukikazeMua** [comment]
thank u
