### ISSUE TITLE
enemy jet

### ISSUE THREAD

**Issue by YukikazeMua** [Xeno69/Domination#495]
How do I add enemy jet, such as  to-201 To attack us

**Comment by Xeno69** [comment]
I can't tell you the class name out of my head, but you have to get the class name of the plane and add it here:
https://github.com/Xeno69/Domination/blob/d7beaf68f829a2ed6b7f0bd9d492830f22a0b667/co30_Domination.Altis/init/fn_preinit.sqf#L1464
when you play blufor. In the next version an array of class names is allowed.
