### ISSUE TITLE
 d_no_3rd_person

### ISSUE THREAD

**Issue by SgtFoose** [Xeno69/Domination#499]
Where do I change the  d_no_3rd_person? I can't enable it from the Params?

https://github.com/Xeno69/Domination/wiki/Params

**Comment by longtimegamer** [comment]
just a heads up, that property was removed.  old changelog:

- Removed: d_no_3rd_person parameter (No 3rd person), allowed 3rd person view in vehicles only. There is now a new A3 game difficulty setting (see https://forums.bohemia.net/forums/topic/140837-development-branch-changelog/?do=findComment&comment=3411692)

**Comment by SgtFoose** [comment]
Ok thanks!

**Comment by SgtFoose** [comment]
Solved
