### ISSUE TITLE
ACE - Sidemission sometimes fail due to Nullobject as killer

### ISSUE THREAD

**Issue by Auge103** [Xeno69/Domination#5]
**Issue:**
When using ACE, sidemissions sometimes fail if the target is killed by ACE logic (i.e. ACE medical system).
When the target gets killed, the killer of 
 `_this addEventhandler ["killed", {_this call d_fnc_KilledSMTargetNormal}];` 
< File: fn_addkillednormal.sqf ,last line >
is sometimes set to `[<NULL-object>]` instead of `[d_alpha_1]` .

**Reproduction:**
Load only sidemission "1" (kill officer) and try to kill him with ace enabled (medical system set to players and ai). Headshots & explosives tend to finish the sidemission, "normal shots" tend to fail it.

//Edit: This seems related: https://github.com/acemod/ACE3/issues/3790

**Comment by Xeno69** [comment]
So how can I disable it for AI completely or for just specific AI units? (without putting modules in a map)

**Comment by Auge103** [comment]
```
force ace_medical_enableFor = 1;
force ace_medical_ai_enabledFor = 2;
force ace_medical_medicSetting = 2;
force ace_medical_level = 2;
force ace_medical_enableAdvancedWounds = true;
```
The top one should do it, the other ones were also set in my tests. I already fixed and tested this issue both in MP and dedicated #https://github.com/Xeno69/Domination/pull/6
