### ISSUE TITLE
Admin reserved slot

### ISSUE THREAD

**Issue by SgtFoose** [Xeno69/Domination#501]
Hi I managed to get the server up and running and added a unit with INIT Admin_1 and I added the admin unit to the server "Role Assignment" page. I can login but I get kicked after 30 seconds because I haven't logged in as an admin?

I added this as well:

***

        // d_reserved_slot gives you the ability to add reserved slots for admins
	// if you don't log in when you've chosen the slot, you'll get kicked after ~20 once the intro ended
	// default is no check, example: d_reserved_slot = ["d_artop_1"];
	if (isNil "d_reserved_slot") then {
		d_reserved_slot = ["Admin_1"];
	};

	// d_uid_reserved_slots and d_uids_for_reserved_slots gives you the possibility to limit a slot
	// you have to add the var names of the units to d_uid_reserved_slots and in d_uids_for_reserved_slots the UIDs of valid players
	// d_uid_reserved_slots = ["d_alpha_1", "d_bravo_3"];
	// d_uids_for_reserved_slots = ["1234567", "7654321"];
	if (isNil "d_uid_reserved_slots") then {
		d_uid_reserved_slots = ["Admin_1"];
		d_uids_for_reserved_slots = ["7656******05164"];
	};
	
***
(I blurred my UDID for this on purpose)

Were do I find the password which is usually in server.cfg but I'm starting the server from the game because UPNP / Port Forward fails if done anotrher way.

**Comment by Xeno69** [comment]
Check here:
https://community.bistudio.com/wiki/Arma_3:_Server_Config_File

**Comment by SgtFoose** [comment]
But I'm running from the game? would it work if I add the server.cfg file and load it from -config on the shortcut of arma.exe (not armaserver.exe)?
