### ISSUE TITLE
admin "end maintarget" sometimes causes createmaintarget to be run twice

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#502]
admin "end maintarget" bug

sometimes createmaintarget is run twice and crashes the server

**Comment by longtimegamer** [comment]
I think @Xeno69 resolved this issue but I will test.

https://github.com/Xeno69/Domination/commit/a3ce3079bc7fe7590bf8b1dab02578c64fea8302

**Comment by longtimegamer** [comment]
unfortunately this is still broken

**Comment by Xeno69** [comment]
Check again, made some more changes.
