### ISSUE TITLE
admin "end main target" does not work when victory condition is set to "AI low"

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#530]
The "end main target" button only sets the properties for victory (number of camps, tower destroyed).  If the victory condition is set to "low AI" then the maintarget will not clear.

The admin function needs to actually remove the enemies or target clear will not run.

**Comment by Xeno69** [comment]
Done

**Comment by longtimegamer** [comment]
I am still having trouble with this on dedicated server.

**Comment by longtimegamer** [comment]
seems to be fixed in latest master
