### ISSUE TITLE
Infantry not generated in barracks

### ISSUE THREAD

**Issue by generation2k15** [Xeno69/Domination#536]
d_ai_awareness_rad

d_snp_aware

d_ai_pursue_rad

d_ai_aggressiveshoot

Modifying these settings will cause problems.

**Comment by Xeno69** [comment]
Thanks for reporting.

@longtimegamer 
Something for you :)

**Comment by Xeno69** [comment]
@generation2k15 
Modifying just one of the settings causes it or a combination?

**Comment by generation2k15** [comment]
Thanks for the reply.
I modified all of the above settings.
The modified values are the same as in the order above.

200

1

150

1

**Comment by Xeno69** [comment]
@longtimegamer 
Check https://github.com/Xeno69/Domination/blob/898c705ff467605d4e11b719703ad8ceebfa49f3/co30_Domination.Altis/server/fn_createmaintarget.sqf#L965

d_c_t_e_u_b is set to true which prevents respawning in the entity killed mission eventhandler. What was the reason for it? (Can't remember :D)

**Comment by longtimegamer** [comment]
I don't know.  Maybe to protect server resources if there are too many AI for the awareness loop?

That is not a problem though.  In my experience the awareness loop manages 200+ AI easily.  Spawning or paradropping a few more should be fine.  I think it can be removed.

**Comment by Xeno69** [comment]
Thanks for the feedback, I'll remove it
