### ISSUE TITLE
where is the code to draw this icon (screenshot)

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#539]
I can't find the code to draw this team score icon:

![image](https://github.com/Xeno69/Domination/assets/46298219/fb5bbd52-7a77-41a7-bf9b-6c7b4f368c13)

**Comment by longtimegamer** [comment]
I would like to add an expression to check isStreamFriendly but I can't find it in the code...

**Comment by Xeno69** [comment]
That's something from Zeus and I have no idea how to remove it

**Comment by Xeno69** [comment]
So you have to search the BI wiki or Google

**Comment by longtimegamer** [comment]
ha yes, that icon is only visible after #login and opening Zeus

thank you, I didn't notice that!
