### ISSUE TITLE
when persistent corpses are enabled and preemptive event runs the maintarget sometimes does not cleanup correctly

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#544]
when a preemptive event runs, clearing a target results in abandoned units

tested on dedicated server

steps to reproduce:

* launch Domination with `d_with_MainTargetEvents` = -5
* clear the maintarget
* observe the new maintarget is created and the old maintarget is not cleared (enemies still alive are not deleted)

**Comment by longtimegamer** [comment]
need to look at this more, might be a bug I created, not sure

**Comment by Xeno69** [comment]
Please look at it as fast as you can!

**Comment by longtimegamer** [comment]
I can reproduce this problem.  I am not sure what is going on.  I also opened a new issue with units spawning at 0,0,0 which might be related.

![image](https://github.com/Xeno69/Domination/assets/46298219/475adb5b-0737-4afe-b9fa-e7b414925f42)

**Comment by longtimegamer** [comment]
I see the end of createmaintarget:

`2023/07/16,  9:34:12 ["end of fn_createmaintarget.sqf"]`

But then I see more vehicles being placed after end of fn:

`2023/07/16,  9:34:33 ["fn_spawnvehicle could not find a flat and empty spot after 99 attempts, giving up and using original position"]`

**Comment by longtimegamer** [comment]
still not sure, target_clear is running but units are not being deleted

**Comment by Xeno69** [comment]
Question: how long did you wait? The deletion of old target units doesn't happen immediately.

**Comment by longtimegamer** [comment]
Hmmm yes, it's more than 90 seconds.

I was looking at d_do_not_delete but I don't see the issue yet.

**Comment by longtimegamer** [comment]
I think we are both working on this.  I see you merged some stuff.  I'm still not sure about the problem.

**Comment by longtimegamer** [comment]
end maintarget button leaves this

![image](https://github.com/Xeno69/Domination/assets/46298219/7f2e32cc-7331-48c9-a695-9e79817bf66d)

**Comment by longtimegamer** [comment]
oh ok, it works now after 90 seconds with the latest master

**Comment by longtimegamer** [comment]
ok something is fixed, at least in local testing

![image](https://github.com/Xeno69/Domination/assets/46298219/f192ce05-9d5e-4d13-8d1f-fd907eb3eac9)

**Comment by longtimegamer** [comment]
Cool, it also works on dedicated server.

What was the fix?  I saw lots of changes from A3_DEV branch...

**Comment by Xeno69** [comment]
The merged DEV changes are mostly related to SPE

**Comment by longtimegamer** [comment]
closing, everything seems to work with latest master

**Comment by longtimegamer** [comment]
This is still a problem but I think it is only a problem with the new preemptive event.  Most servers will not be affected.

**Comment by longtimegamer** [comment]
#515 might fix this issue

**Comment by longtimegamer** [comment]
#551 might fix this issue

**Comment by longtimegamer** [comment]
still not fixed

tricky bug :(

**Comment by longtimegamer** [comment]
#553 might fix this

**Comment by longtimegamer** [comment]
nope, still broken!

this one is making me crazy

**Comment by longtimegamer** [comment]
still broken!

:|

**Comment by longtimegamer** [comment]
wait.................... using the wrong code, might not be broken

I will leave this issue open for a while until I can confirm it is fixed.

**Comment by longtimegamer** [comment]
yes, this is fixed
