### ISSUE TITLE
stringtable and next-line characters

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#550]
I am seeing "\n" at the end of some strings in the kbtell

example:

STR_DOM_MISSIONSTRING_565

**Comment by longtimegamer** [comment]
I don't remember seeing this, perhaps going crazy...

**Comment by longtimegamer** [comment]
I can't reproduce now but... I saw it I saw it!

We should probably remove the \n from all strings anyway.  I don't think they work.

**Comment by Xeno69** [comment]
Check https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/client/fn_hintchatmsg.sqf
