### ISSUE TITLE
The Chinese translation contain advertisement

### ISSUE THREAD

**Issue by teemo0803** [Xeno69/Domination#56]
line 1743 <Chinesesimp>中国军事模拟联盟QQ群:422522513</Chinesesimp>
line 1753 <Chinesesimp>语音TS服务器:ts.msuoc.cn</Chinesesimp>
I recommend to change that into:
line 1743 <Chinesesimp>欢迎进入Domination任务</Chinesesimp> //welcom to domination server
line 1753 <Chinesesimp>祝您游戏愉快</Chinesesimp> //I wish you a happy game

Hope to adopt.Thanks!

**Comment by teemo0803** [comment]
in stringtable.xml

**Comment by Xeno69** [comment]
That's already fixed for the next update :)

**Comment by teemo0803** [comment]
thanks
