### ISSUE TITLE
hide camp 3D markers in player HUD

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#566]
I would like to be able to hide the camp markers in the player 3D HUD.

Example marker for camp 3:

![image](https://github.com/Xeno69/Domination/assets/46298219/81724c1d-d24f-43d7-926e-4d905064ec4f)

I can't find where this marker is created.  Any help?  Hopefully not in the camps FSM... :|

**Comment by Xeno69** [comment]
Check
https://github.com/Xeno69/Domination/blob/d004981153cf0195a54311335f0debab980aad77/co30_Domination.Altis/clientui/fn_draw3dstuff.sqf#L57
