### ISSUE TITLE
russian translation

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#57]
https://drive.google.com/open?id=1uA06fvh_-4BgG0gFsPt0YHV1ro13k-Um

Hi Xeno! pls add to next update some fixes of rus transl +new transl. Thx

**Comment by Xeno69** [comment]
You can always see the latest stringtable.xml file here:
https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/stringtable.xml

**Comment by topden** [comment]
ok. last update https://drive.google.com/open?id=1FXBeC_L85_zePFgpKIUqIyfvGwMsl6jz

**Comment by topden** [comment]
I looked and added a translation of three more lines. through some menu, but I do not really know how to use the github and ask to check it just in case  (str_1949,1950,1951)
