### ISSUE TITLE
some items in coop 3.99o opfor rhs

### ISSUE THREAD

**Issue by topden** [Xeno69/Domination#58]
haven't next items in arsenal in all ranks:
1 radioitem http://joxi.ru/bmoJENgH3M6D7r
2 binoculars at least  http://joxi.ru/D2Pdz7LcqdM0R2
3. mine-detector,  toolkit  http://joxi.ru/xAeBg3MCRYW97r

I have maximum rank but dont know where i can take radio http://joxi.ru/krDRzKMHK01p32  )) and others items.

mods: only cba & rhs

**Comment by Xeno69** [comment]
Oh ok, I didn't do the ranked items, weapons, uniforms, etc, class names myself, I'll add them for the next version.
