### ISSUE TITLE
number of maintargets is not set by d_MainTargets_num

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#582]
steps to reproduce:

* set `d_MainTargets_num` to a low number (2)
* use Admin Dialog -> End Maintarget
* targets continue to spawn after the configured number

probably a bug here:

https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/d_init.sqf#L462-L464

EDIT: ok not there but somewhere near

**Comment by Xeno69** [comment]
So what are the settings param settings if it happens?

I saw it your chat on Discord, always ask for a RPT file (where the param values are printed out at mission start)

**Comment by longtimegamer** [comment]
yes, collecting the RPT is good advice

**Comment by longtimegamer** [comment]
I am able to reproduce this issue.  It doesn't seem like `d_MainTargets_num` has any affect.

**Comment by Xeno69** [comment]
I think what you are missing is that as soon as target selection is enabled all targets are used (d_with_targetselect_count > 0). When target selection is disabled, selected number of targets is chosen.

**Comment by Xeno69** [comment]
Closing this. Please reopen or make a new ticket if there are still issues.

**Comment by longtimegamer** [comment]
> I think what you are missing is that as soon as target selection is enabled all targets are used (d_with_targetselect_count > 0).

Understood.  I missed that, thank you.
