### ISSUE TITLE
Error message "Bad vehicle  C_man_p_beggar_F_tanoan"

### ISSUE THREAD

**Issue by Xeno69** [Xeno69/Domination#583]
![image](https://github.com/Xeno69/Domination/assets/3141271/d10f4786-bbab-4c57-be9c-f5147d0c240f)

**Comment by longtimegamer** [comment]
unit type does not exist, fixed

https://github.com/Xeno69/Domination/pull/585/commits/592db099f8f3891fc05728989e078a895acb6b84
