### ISSUE TITLE
为什么其他都是中文的字幕还是英文的啊

### ISSUE THREAD

**Issue by 3032028472** [Xeno69/Domination#592]
![微信图片_20231026222004](https://github.com/Xeno69/Domination/assets/103985316/e452b180-3f62-4776-9646-00ea46b9d2ae)

**Comment by longtimegamer** [comment]
"Why are the other subtitles in English?"

We need volunteers to help translate many subtitles in many languages.

We have a long list of subtitles which require translation.  All help is appreciated!

https://github.com/Xeno69/Domination/blob/master/missing_translations/Chinese.txt

https://github.com/Xeno69/Domination/blob/master/missing_translations/Chinesesimp.txt

https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/stringtable.xml

**Comment by 3032028472** [comment]
> “为什么其他字幕都是英文的？”
> 
> 我们需要志愿者帮助翻译多种语言的许多字幕。
> 
> 我们有一长串需要翻译的字幕。感谢所有帮助！
> 
> https://github.com/Xeno69/Domination/blob/master/missing_translations/Chinese.txt
> 
> https://github.com/Xeno69/Domination/blob/master/missing_translations/Chinesesimp.txt
> 
> https://github.com/Xeno69/Domination/blob/master/co30_Domination.Altis/stringtable.xml

But I host multiplayer games on my computer with Chinese subtitles, and put the task on a dedicated server and it becomes English

**Comment by longtimegamer** [comment]
look at the server configuration

`language="English";`

https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server_(Chinese_Simplified)

**Comment by 3032028472** [comment]
> 查看服务器配置
> 
> `language="English";`
> 
> [https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server_（Chinese_Simplified）](https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server_(Chinese_Simplified))

我的服务器配置文件是language="English";但是还是英文

**Comment by 3032028472** [comment]
> look at the server configuration
> 
> `language="English";`
> 
> https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server_(Chinese_Simplified)

My server configuration file is language="English"; But it's still in English

**Comment by 3032028472** [comment]
I saw this in the official documentation
![Uploading 捕获.JPG…]()

**Comment by Xeno69** [comment]
Normally the language setting, even in multiplayer, is done on the client side.

I know that both Chinese translations work. So something is not correct. Check your Arma 3 settings and/or installation.

**Comment by 3032028472** [comment]
> 通常，即使在多人游戏中，语言设置也是在客户端完成的。
> 
> 我知道这两种中文翻译都有效。所以有些事情是不正确的。检查您的 Arma 3 设置和/或安装。


It's strange that only the subtitles are in English. I've been working on them for a long time and I don't know where I made a mistake

**Comment by longtimegamer** [comment]
I am sorry but I don't know how to help.  Different versions of Domination?  Many new items have been translated in the past years.  I am not certain.
