### ISSUE TITLE
The gas leak mission is not working properly.

### ISSUE THREAD

**Issue by generation2k15** [Xeno69/Domination#603]
I'm running latest ver altis.pbo with dedicated server.

I can't find any interaction. Is this just me?

**Comment by Xeno69** [comment]
Which version were you playing?

**Comment by generation2k15** [comment]
> Which version were you playing?

I used this
co40_domination_4_69_blufor.altis

**Comment by Xeno69** [comment]
Just tested both gas leak missions on Altis. Both work totally fine.
Any more information?

**Comment by generation2k15** [comment]
> Just tested both gas leak missions on Altis. Both work totally fine. Any more information?

I remember the area where I found the problem as #41. All I did was run the server through the arma3 faster program.

**Comment by Xeno69** [comment]
What is the A3 faster program?

**Comment by generation2k15** [comment]
> What is the A3 faster program?

here
https://github.com/Foxlider/FASTER

**Comment by Xeno69** [comment]
Can't reproduce. Please reopen if it happens again (and with more info)
