### ISSUE TITLE
New zone is immediately seized after being created

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#625]
on behalf of XOR

When seize condition is set to all camps captured and radio tower destroyed
New zone is immediately seized after being created, since there are no camps or radio towers (yet)
'Seized' zone is populated with camps, radio tower & AI despite having  been seized 
Zone selection starts for yet another zone, but since previous zone is populated new zone doesn't get seized after creation
There are now two populated zones, only one of which can be seized
Zone may not be the most accurate word to describe AO's, but found it most fitting to describe the problem

To reproduce; 
set seize condition to all camps captured and radio tower destroyed
use admin dialogue to complete main objective

![image](https://github.com/Xeno69/Domination/assets/46298219/8b1eda3a-39b4-49fe-b0ce-66c52ffde3cb)

**Comment by Xeno69** [comment]
That was already fixed some time ago and will be available when 4.70 gets released.

**Comment by longtimegamer** [comment]
I entered a bug I already fixed lol

big brain moment

**Comment by longtimegamer** [comment]
duplicate of #594
