### ISSUE TITLE
vehicle targets for players in jets

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#626]
> Long time Domi player.  I've always loved jets.   Is there a way to spawn enemy vehicles (not infantry) based on a larger radius just for players in aircraft?  Looking for a way to get more battlefield activity for players in jets (ie just vehicles) without spawning all the enemy infantry and kill performance.  Just curious. Maybe not possible.

> that's a cool idea, vehicle targets to keep jet pilots busy.  vehicles without enemy drivers may not be identified as Opfor, however.  i will need to think about it.

> Could it work similar to the island patrols?
I always loved the idea of each map starting with pre placed AAA emplacements that need to be neutralised to enable availability of friendly air

**Comment by longtimegamer** [comment]
I am thinking about implementing this.

I think the old island patrol is disabled now?  d_with_isledefense isn't initialized by default that I can see.

Maybe a param setting when true an event "Respond to CAS Airstrike Request" occurs.  Spawn a few targets.  Cleanup later.

**Comment by Xeno69** [comment]
Island patrol is on as default.

**Comment by longtimegamer** [comment]
thanks, it was disabled and I did not notice

**Comment by longtimegamer** [comment]
my attempt:

https://github.com/Xeno69/Domination/pull/633
