### ISSUE TITLE
Domination mission parameters configurable by properties file

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#63]
Is it possible for the mission parameters to be driven by file-based properties?

As an admin I use "#missions" to select the mission and then set the many, many mission parameters.  As an example, my "taste" in Domination requires perhaps 20+ changes to the default parameters.  So many clicks!  (Or arrow keys!)  Also the desired mission parameters are lost if the mission is stopped for any reason (because only "#restart" will remember mission settings).  For this reason, many admins choose to download the code here to make changes and create custom PBOs for each update.

If there was a way to read defaults from a properties file then server admins would be able to use the "vanilla" Domination release PBOs and leave a properties file with the desired server tweaks in mpmissions folder (or wherever seems best).  There are many properties that would be more accessible for tweaks, specifically the properties defined in description.ext, initcommon.sqf and fn_changeskill.sqf.  It would be great to just create a few overrides in a text file once and after that each Domination release is just drop-and-replace for the new PBO.

What do you think?  I could try to implement this myself too.  Happy to try if you don't mind cleaning up my mistakes.  :)

**Comment by Xeno69** [comment]
Simply use a SQL database and start the server with extDB3 and you can change all params in CfgParams in a database table and many other settings in the settings table.

The mission will then allways use the database values

**Comment by longtimegamer** [comment]
That's perfect, thanks.
