### ISSUE TITLE
I lost my points Domination 1

### ISSUE THREAD

**Issue by JOCER2** [Xeno69/Domination#639]
Hello Xeno,
There was a server outage Saturday Jun 1st evening at midnight on Domination 1 and when I came back on the server, I lost my rank and my points.
I was at 29400 points and I lost everything. Now I'm at 0 !
Can you give them to me?
My name on the game is JOCER
Can you help me please ?
Thanks in advance.

**Comment by Xeno69** [comment]
You have to ask the server owner. I don't run any servers and there is no central points database.
