### ISSUE TITLE
d_MainTargets_num texts[] is undefined in SPE version

### ISSUE THREAD

**Issue by kju** [Xeno69/Domination#647]
![image](https://github.com/user-attachments/assets/784a0c31-ed71-4774-9496-9159c239b63c)

**Comment by Xeno69** [comment]
For now you can copy the texts array from __GMCWG__
No new Domi release before A3 2.18 (yeah, waiting for ages for 2.18)

**Comment by kju** [comment]
thanks 👍 no problem to wait
