### ISSUE TITLE
Is external DB still needed for 'mission parameters', 'mission progress' and 'mission progress'

### ISSUE THREAD

**Issue by kju** [Xeno69/Domination#651]
> Domination can persist data with a properly configured database. Setting up a database is optional. Domination will function normally without any external database.
> 
> With a connected database the following Domination data will be preserved across server reboots:
> 
> mission parameters
> mission progress
> player scores and ranks

from https://github.com/Xeno69/Domination/wiki/Administrator-Guide#database-setup

as you are using https://community.bistudio.com/wiki/missionProfileNamespace - is the docu still up-to-date in that regard or if not, I am curious why these three are not covered by mPNS. is it too unsafe or too much data?

**Comment by Xeno69** [comment]
I would recommend a SQL DB if you have  many different players but otherwise missionProfileNamespace is just fine.

**Comment by kju** [comment]
copy 👍
