### ISSUE TITLE
players sometimes spawning over water upon first life in a mission

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#89]
Players report spawning over water and dying/washing up on shore.  This consistently affects some players while others are not affected at all.  This only occurs on the first "life" of the mission, subsequently the players can spawn correctly.

**Comment by Xeno69** [comment]
Are you talking about players which just connected or players who died the first time?

**Comment by longtimegamer** [comment]
The players die instantly upon spawning.  But only once.

Some unlucky players will see this exactly once every time they connect to the server, choose a slot and click "continue."  This also happens exactly once if the mission is restarted with #restart and the unlucky player is connected.  Approximately one in four players seem to be affected.  The other players never experience the bug, not even once (like me).

**Comment by Xeno69** [comment]
Which mission? I mean which version? I've never encountered it because player units are just editor placed and I don't move them via script.

**Comment by longtimegamer** [comment]
This was Altis using v4.01.  I wish I could describe the problem more but I have personally never seen it.  My description here is collected from several other players.  I can try to collect more information but I am not sure what would help... I am not sure if a RPT is useful in this case and the server log at default log level does not show any useful information.

What to do?

**Comment by Xeno69** [comment]
Well, what is needed is a RPT file from a player when it happens...

Are you playing with mods?

I've played online now with about 30 players and no problem at all.

**Comment by longtimegamer** [comment]
No mods, vanilla everything on a Windows server.  I have seen multiple people affected.  Very strange...

I cannot reproduce the issue but I will try to collect an RPT file from a player.

**Comment by longtimegamer** [comment]
I saw the bug and retained the RPT file.  See attached.  There are numerous messages saying "setting invalid pitch 0.0000" and maybe some other clues.

**Comment by longtimegamer** [comment]
[Arma3_x64_2019-07-28_01-11-32.rpt.txt](https://github.com/Xeno69/Domination/files/3438894/Arma3_x64_2019-07-28_01-11-32.rpt.txt)

**Comment by Xeno69** [comment]
Please don't use the git version but one of the versions in the 7zip File

I've played last night with 30 players for an hour and not once the error occurred.

Also make sure that if you don't use Global Mobilization that the server and the players don't load it, same for Contact

The RPT has lots of messages that I do not get myself...

**Comment by longtimegamer** [comment]
Still trying to collect a player RPT for this issue but it is still occurring several times per day.  The server log is very uninteresting... "player spawned, player killed" ...not much information.   I hope we can see a player RPT file for this, still watching for it.

**Comment by MrCraigTunstall** [comment]
@Xeno69 - this happens in the mission file "co40_domination_4_01_blufor.altis"

**Comment by Xeno69** [comment]
Well, the playable units are editor placed and the mission does not move player units when they connect.
And I personally haven't seen it yet (even after playing online for hours, se for all the other players playing with me)

**Comment by longtimegamer** [comment]
> So what's different in your setting?

Not sure.  The server usually starts with a few non-default settings (AI enabled, MHQ teleport block disabled, capture town just checks towers, place first tower near center, civs and more).  Just mission parameters and using recent Domination release from 7zip and usually runs with one HC.

**Comment by Xeno69** [comment]
Fixed in 4.0, I have moved one group accidentally outside the map in the Altis Blufor version
