### ISSUE TITLE
when mission "place first tower near center of town" is true then the players cannot capture tower #1

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#91]
Steps to reproduce:

*mission parameters -> place the first tower near the center of town -> true
*start mission
*observe on map, tower #1 is not marked but does exist (should be near gold marker for main target)
*attempt to capture the tower, observe the "capture tower" message appears but never progresses

**Comment by Xeno69** [comment]
Hm, I never really tested this... Will check it
