### ISSUE TITLE
jets on Malden Blufor airfield

### ISSUE THREAD

**Issue by longtimegamer** [Xeno69/Domination#98]
There are Blufor jets on Malden.  Is that intentional?

**Comment by Xeno69** [comment]
Meh, no, only for the NBV version.
They slipped through for the normal version :(

At least it is not a gamebreaking bug :)

NBV means, you won't get any special vehicles when solving a sidemissions but editor placed units have the same features. Means, if killed you have to use a wreck chopper.

**Comment by Xeno69** [comment]
Forgot that I have both version :P

**Comment by Xeno69** [comment]
Dann, I forgot this one for 4.05 :(
